// AUTO-GENERATED by numeric_limits_gen.py - DO NOT EDIT BY HAND
// Leibniz HPC Math Library - NumericLimits
// All FP values use hex float literals (0x1.XXXp+N) for exact representation.

#pragma once
#include "LeibnizFloat.h"
#include "LeibnizInt.h"

namespace Leibniz::Numerics::Limits {

	template<typename T>
	struct NumericLimits;

	// TODO Not added Fp16 and Bf16
	/* 
	// FP16  (Float16)  mantissa=10  exponent=5  bias=15

	template<>
	struct NumericLimits<Float16> final {
		static constexpr int mantissaBits = 10;
		static constexpr int exponentBits = 5;
		static constexpr int exponentBias = 15;
		static constexpr int maxExponent = 15;
		static constexpr int minExponent = -14;
		static constexpr int digits10 = 3;
		static constexpr int maxDigits10 = 5;

		static constexpr Float16 epsilon() noexcept { return 0x1.0p-10; } // 2^(-mantissaBits)
		static constexpr Float16 sqrtEpsilon() noexcept { return 0x1.0p-5; } // sqrt(epsilon)
		static constexpr Float16 minNormal() noexcept { return 0x1.0p-14; } // smallest positive normal
		static constexpr Float16 minSubnormal() noexcept { return 0x1.0p-24; } // smallest positive subnormal
		static constexpr Float16 max() noexcept { return 0x1.ffcp+15; } // largest finite value
	};

	// BF16  (BFloat16)  mantissa=7  exponent=8  bias=127

	
	template<>
	struct NumericLimits<BFloat16> final {
		static constexpr int mantissaBits = 7;
		static constexpr int exponentBits = 8;
		static constexpr int exponentBias = 127;
		static constexpr int maxExponent = 127;
		static constexpr int minExponent = -126;
		static constexpr int digits10 = 2;
		static constexpr int maxDigits10 = 4;

		static constexpr BFloat16 epsilon() noexcept { return 0x1.0p-7; } // 2^(-mantissaBits)
		static constexpr BFloat16 sqrtEpsilon() noexcept { return 0x1.6ap-4; } // sqrt(epsilon)
		static constexpr BFloat16 minNormal() noexcept { return 0x1.0p-126; } // smallest positive normal
		static constexpr BFloat16 minSubnormal() noexcept { return 0x1.0p-133; } // smallest positive subnormal
		static constexpr BFloat16 max() noexcept { return 0x1.fep+127; } // largest finite value
	};

	*/

	// FP32  (Float32)  mantissa=23  exponent=8  bias=127

	template<>
	struct NumericLimits<Float32> final {
		static constexpr int mantissaBits = 23;
		static constexpr int exponentBits = 8;
		static constexpr int exponentBias = 127;
		static constexpr int maxExponent = 127;
		static constexpr int minExponent = -126;
		static constexpr int digits10 = 6;
		static constexpr int maxDigits10 = 9;

		static constexpr float epsilon() noexcept { return 0x1.0p-23f; } // 2^(-mantissaBits)
		static constexpr float sqrtEpsilon() noexcept { return 0x1.6a09e6p-12f; } // sqrt(epsilon)
		static constexpr float minNormal() noexcept { return 0x1.0p-126f; } // smallest positive normal
		static constexpr float minSubnormal() noexcept { return 0x1.0p-149f; } // smallest positive subnormal
		static constexpr float max() noexcept { return 0x1.fffffep+127f; } // largest finite value
	};

	// FP64  (Float64)  mantissa=52  exponent=11  bias=1023

	template<>
	struct NumericLimits<Float64> final {
		static constexpr int mantissaBits = 52;
		static constexpr int exponentBits = 11;
		static constexpr int exponentBias = 1023;
		static constexpr int maxExponent = 1023;
		static constexpr int minExponent = -1022;
		static constexpr int digits10 = 15;
		static constexpr int maxDigits10 = 17;

		static constexpr double epsilon() noexcept { return 0x1.0p-52; } // 2^(-mantissaBits)
		static constexpr double sqrtEpsilon() noexcept { return 0x1.0p-26; } // sqrt(epsilon)
		static constexpr double minNormal() noexcept { return 0x1.0p-1022; } // smallest positive normal
		static constexpr double minSubnormal() noexcept { return 0x1.0p-1074; } // smallest positive subnormal
		static constexpr double max() noexcept { return 0x1.fffffffffffffp+1023; } // largest finite value
	};

	// FP128  (Float128)  mantissa=112  exponent=15  bias=16383
	// Status: STUB - wire up Float128 type first

	template<>
	struct NumericLimits<Float128> final {
		static constexpr int mantissaBits = 112;
		static constexpr int exponentBits = 15;
		static constexpr int exponentBias = 16383;
		static constexpr int maxExponent = 16383;
		static constexpr int minExponent = -16382;
		static constexpr int digits10 = 33;
		static constexpr int maxDigits10 = 36;

		// 2^(-mantissaBits): 0x1.0p-112
		static constexpr double epsilon() noexcept { return /* TODO */ 0.0; }
		// sqrt(epsilon): 0x1.0p-56
		static constexpr double sqrtEpsilon() noexcept { return /* TODO */ 0.0; }
		// smallest positive normal: 0x1.0p-16382
		static constexpr double minNormal() noexcept { return /* TODO */ 0.0; }
		// smallest positive subnormal: 0x1.0p-16494
		static constexpr double minSubnormal() noexcept { return /* TODO */ 0.0; }
		// largest finite value: 0x1.ffffffffffffffffffffffffffffp+16383
		static constexpr double max() noexcept { return /* TODO */ 0.0; }
	};

	// FP256  (Float256)  mantissa=232  exponent=23  bias=4194303
	// Status: STUB - wire up Float256 type first

	template<>
	struct NumericLimits<Float256> final {
		static constexpr int mantissaBits = 232;
		static constexpr int exponentBits = 23;
		static constexpr int exponentBias = 4194303;
		static constexpr int maxExponent = 4194303;
		static constexpr int minExponent = -4194302;
		static constexpr int digits10 = 69;
		static constexpr int maxDigits10 = 72;

		// 2^(-mantissaBits): 0x1.0p-232
		static constexpr double epsilon() noexcept { return /* TODO */ 0.0; }
		// sqrt(epsilon): 0x1.0p-116
		static constexpr double sqrtEpsilon() noexcept { return /* TODO */ 0.0; }
		// smallest positive normal: 0x1.0p-4194302
		static constexpr double minNormal() noexcept { return /* TODO */ 0.0; }
		// smallest positive subnormal: 0x1.0p-4194534
		static constexpr double minSubnormal() noexcept { return /* TODO */ 0.0; }
		// largest finite value: 0x1.ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffp+4194303
		static constexpr double max() noexcept { return /* TODO */ 0.0; }
	};

	// FP512  (Float512)  mantissa=479  exponent=32  bias=2147483647
	// Status: STUB - wire up Float512 type first

	template<>
	struct NumericLimits<Float512> final {
		static constexpr int mantissaBits = 479;
		static constexpr int exponentBits = 32;
		static constexpr int exponentBias = 2147483647;
		static constexpr int maxExponent = 2147483647;
		static constexpr int minExponent = -2147483646;
		static constexpr int digits10 = 144;
		static constexpr int maxDigits10 = 146;

		// 2^(-mantissaBits): 0x1.0p-479
		static constexpr double epsilon() noexcept { return /* TODO */ 0.0; }
		// sqrt(epsilon): 0x1.6a09e667f3bcc908b2fb1366ea957d3e3adec17512775099da2f590b0667322a95f90608757145875163fcdfb907b6721ee950bc8738f694f0090e6cp-240
		static constexpr double sqrtEpsilon() noexcept { return /* TODO */ 0.0; }
		// smallest positive normal: 0x1.0p-2147483646
		static constexpr double minNormal() noexcept { return /* TODO */ 0.0; }
		// smallest positive subnormal: 0x1.0p-2147484125
		static constexpr double minSubnormal() noexcept { return /* TODO */ 0.0; }
		// largest finite value: 0x1.fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffep+2147483647
		static constexpr double max() noexcept { return /* TODO */ 0.0; }
	};

	// FP1024  (Float1024)  mantissa=991  exponent=32  bias=2147483647
	// Status: STUB - wire up Float1024 type first

	template<>
	struct NumericLimits<Float1024> final {
		static constexpr int mantissaBits = 991;
		static constexpr int exponentBits = 32;
		static constexpr int exponentBias = 2147483647;
		static constexpr int maxExponent = 2147483647;
		static constexpr int minExponent = -2147483646;
		static constexpr int digits10 = 298;
		static constexpr int maxDigits10 = 300;

		// 2^(-mantissaBits): 0x1.0p-991
		static constexpr double epsilon() noexcept { return /* TODO */ 0.0; }
		// sqrt(epsilon): 0x1.6a09e667f3bcc908b2fb1366ea957d3e3adec17512775099da2f590b0667322a95f90608757145875163fcdfb907b6721ee950bc8738f694f0090e6c7bf44ed1a4405d0e855e3e9ca60b38c0237866f7956379222d108b148c1578e45ef89c678dab5147176fd3b99654c68663e7909bea5e241f06dcb05dd5494114p-496
		static constexpr double sqrtEpsilon() noexcept { return /* TODO */ 0.0; }
		// smallest positive normal: 0x1.0p-2147483646
		static constexpr double minNormal() noexcept { return /* TODO */ 0.0; }
		// smallest positive subnormal: 0x1.0p-2147484637
		static constexpr double minSubnormal() noexcept { return /* TODO */ 0.0; }
		// largest finite value: 0x1.fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffep+2147483647
		static constexpr double max() noexcept { return /* TODO */ 0.0; }
	};

	// =====================================================================
	// Integer Limits
	// =====================================================================

	template<typename T>
	struct IntegerLimits;

	// Int8  (8-bit signed)

	template<>
	struct IntegerLimits<Byte> final {
		static constexpr int bits = 8;

		static constexpr signed char min() noexcept { return -128; }
		static constexpr signed char max() noexcept { return 127; }
	};

	// UInt8  (8-bit unsigned)

	template<>
	struct IntegerLimits<UByte> final {
		static constexpr int bits = 8;

		static constexpr unsigned char min() noexcept { return 0; }
		static constexpr unsigned char max() noexcept { return 255; }
	};

	// Int16  (16-bit signed)

	template<>
	struct IntegerLimits<Int16> final {
		static constexpr int bits = 16;

		static constexpr short min() noexcept { return -32768; }
		static constexpr short max() noexcept { return 32767; }
	};

	// UInt16  (16-bit unsigned)

	template<>
	struct IntegerLimits<UInt16> final {
		static constexpr int bits = 16;

		static constexpr unsigned short min() noexcept { return 0; }
		static constexpr unsigned short max() noexcept { return 65535; }
	};

	// Int32  (32-bit signed)

	template<>
	struct IntegerLimits<Int32> final {
		static constexpr int bits = 32;

		static constexpr int min() noexcept { return -2147483648; }
		static constexpr int max() noexcept { return 2147483647; }
	};

	// UInt32  (32-bit unsigned)

	template<>
	struct IntegerLimits<UInt32> final {
		static constexpr int bits = 32;

		static constexpr unsigned int min() noexcept { return 0; }
		static constexpr unsigned int max() noexcept { return 4294967295ULL; }
	};

	// Int64  (64-bit signed)

	template<>
	struct IntegerLimits<Int64> final {
		static constexpr int bits = 64;

		static constexpr long long min() noexcept { return -9223372036854775807LL - 1; }
		static constexpr long long max() noexcept { return 9223372036854775807LL; }
	};

	// UInt64  (64-bit unsigned)

	template<>
	struct IntegerLimits<UInt64> final {
		static constexpr int bits = 64;

		static constexpr unsigned long long min() noexcept { return 0; }
		static constexpr unsigned long long max() noexcept { return 18446744073709551615ULL; }
	};

	// Int128  (128-bit signed)

	template<>
	struct IntegerLimits<Int128> final {
		static constexpr int bits = 128;

		// min: -0x80000000000000000000000000000000
		// max: 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
		static constexpr long long min() noexcept { return /* TODO */ 0; }
		static constexpr long long max() noexcept { return /* TODO */ 0; }
	};

	// UInt128  (128-bit unsigned)

	template<>
	struct IntegerLimits<UInt128> final {
		static constexpr int bits = 128;

		// min: 0x0
		// max: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
		static constexpr long long min() noexcept { return /* TODO */ 0; }
		static constexpr long long max() noexcept { return /* TODO */ 0; }
	};

	// Int256  (256-bit signed)

	template<>
	struct IntegerLimits<Int256> final {
		static constexpr int bits = 256;

		// min: -0x8000000000000000000000000000000000000000000000000000000000000000
		// max: 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
		static constexpr long long min() noexcept { return /* TODO */ 0; }
		static constexpr long long max() noexcept { return /* TODO */ 0; }
	};

	// UInt256  (256-bit unsigned)

	template<>
	struct IntegerLimits<UInt256> final {
		static constexpr int bits = 256;

		// min: 0x0
		// max: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
		static constexpr long long min() noexcept { return /* TODO */ 0; }
		static constexpr long long max() noexcept { return /* TODO */ 0; }
	};

	// Int512  (512-bit signed)

	template<>
	struct IntegerLimits<Int512> final {
		static constexpr int bits = 512;

		// min: -0x80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
		// max: 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
		static constexpr long long min() noexcept { return /* TODO */ 0; }
		static constexpr long long max() noexcept { return /* TODO */ 0; }
	};

	// UInt512  (512-bit unsigned)

	template<>
	struct IntegerLimits<UInt512> final {
		static constexpr int bits = 512;

		// min: 0x0
		// max: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
		static constexpr long long min() noexcept { return /* TODO */ 0; }
		static constexpr long long max() noexcept { return /* TODO */ 0; }
	};

	// Int1024  (1024-bit signed)

	template<>
	struct IntegerLimits<Int1024> final {
		static constexpr int bits = 1024;

		// min: -0x8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
		// max: 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
		static constexpr long long min() noexcept { return /* TODO */ 0; }
		static constexpr long long max() noexcept { return /* TODO */ 0; }
	};

	// UInt1024  (1024-bit unsigned)

	template<>
	struct IntegerLimits<UInt1024> final {
		static constexpr int bits = 1024;

		// min: 0x0
		// max: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
		static constexpr long long min() noexcept { return /* TODO */ 0; }
		static constexpr long long max() noexcept { return /* TODO */ 0; }
	};
} // namespace Leibniz::Numerics::Limits