// AUTO-GENERATED by math_constants_gen.py - DO NOT EDIT BY HAND
// Leibniz HPC Math Library - Mathematical Constants
// All values use hex float literals (0x1.XXXp+N) for exact representation.
//
// Live:  Float32, Float64
// Stubs: Float128 / Float256 / Float512 / Float1024 (hex in comments, double fallback)

#pragma once
#include "LeibnizFloat.h"

namespace Leibniz::Numerics::Constants {
	template<typename T>
	struct MathConstants;

	// Float32 (f32, 23-bit mantissa)
	template<>
	struct MathConstants<Float32> final {
		// Core
		static constexpr float pi() noexcept { return 0x1.921fb6p+1f; } // pi
		static constexpr float tau() noexcept { return 0x1.921fb6p+2f; } // 2*pi
		static constexpr float euler() noexcept { return 0x1.5bf0a8p+1f; } // Euler's number e
		static constexpr float sqrt2() noexcept { return 0x1.6a09e6p+0f; } // sqrt(2)
		static constexpr float sqrt3() noexcept { return 0x1.bb67aep+0f; } // sqrt(3)
		static constexpr float sqrt5() noexcept { return 0x1.1e377ap+1f; } // sqrt(5)
		static constexpr float goldenRatio() noexcept { return 0x1.9e377ap+0f; } // (1+sqrt(5))/2

		// Logarithmic
		static constexpr float ln2() noexcept { return 0x1.62e43p-1f; } // log_e(2)
		static constexpr float ln10() noexcept { return 0x1.26bb1cp+1f; } // log_e(10)
		static constexpr float log2e() noexcept { return 0x1.715476p+0f; } // log_2(e) = 1/ln2
		static constexpr float log10e() noexcept { return 0x1.bcb7b2p-2f; } // log_10(e) = 1/ln10
		static constexpr float log2_10() noexcept { return 0x1.a934fp+1f; } // log_2(10)
		static constexpr float log10_2() noexcept { return 0x1.344136p-2f; } // log_10(2)

		// Inverses
		static constexpr float invPi() noexcept { return 0x1.45f306p-2f; } // 1/pi
		static constexpr float invTwoPi() noexcept { return 0x1.45f306p-3f; } // 1/(2*pi)
		static constexpr float invE() noexcept { return 0x1.78b564p-2f; } // 1/e
		static constexpr float invLn2() noexcept { return 0x1.715476p+0f; } // 1/ln2
		static constexpr float invLn10() noexcept { return 0x1.bcb7b2p-2f; } // 1/ln10

		// Angle
		static constexpr float degToRad() noexcept { return 0x1.1df46ap-6f; } // pi/180
		static constexpr float radToDeg() noexcept { return 0x1.ca5dc2p+5f; } // 180/pi

		// Special
		static constexpr float eulerMascheroni() noexcept { return 0x1.2788dp-1f; } // Euler-Mascheroni gamma
		static constexpr float catalan() noexcept { return 0x1.d4f972p-1f; } // Catalan's constant G
		static constexpr float apery() noexcept { return 0x1.33bap+0f; } // Apery's constant zeta(3)
	};

	// Float64 (f64, 52-bit mantissa)

	template<>
	struct MathConstants<Float64> final {
		// Core
		static constexpr double pi() noexcept { return 0x1.921fb54442d18p+1; } // pi
		static constexpr double tau() noexcept { return 0x1.921fb54442d18p+2; } // 2*pi
		static constexpr double euler() noexcept { return 0x1.5bf0a8b145769p+1; } // Euler's number e
		static constexpr double sqrt2() noexcept { return 0x1.6a09e667f3bcdp+0; } // sqrt(2)
		static constexpr double sqrt3() noexcept { return 0x1.bb67ae8584caap+0; } // sqrt(3)
		static constexpr double sqrt5() noexcept { return 0x1.1e3779b97f4a8p+1; } // sqrt(5)
		static constexpr double goldenRatio() noexcept { return 0x1.9e3779b97f4a8p+0; } // (1+sqrt(5))/2

		// Logarithmic
		static constexpr double ln2() noexcept { return 0x1.62e42fefa39efp-1; } // log_e(2)
		static constexpr double ln10() noexcept { return 0x1.26bb1bbb55516p+1; } // log_e(10)
		static constexpr double log2e() noexcept { return 0x1.71547652b82fep+0; } // log_2(e) = 1/ln2
		static constexpr double log10e() noexcept { return 0x1.bcb7b1526e50ep-2; } // log_10(e) = 1/ln10
		static constexpr double log2_10() noexcept { return 0x1.a934f0979a371p+1; } // log_2(10)
		static constexpr double log10_2() noexcept { return 0x1.34413509f79ffp-2; } // log_10(2)

		// Inverses
		static constexpr double invPi() noexcept { return 0x1.45f306dc9c883p-2; } // 1/pi
		static constexpr double invTwoPi() noexcept { return 0x1.45f306dc9c883p-3; } // 1/(2*pi)
		static constexpr double invE() noexcept { return 0x1.78b56362cef38p-2; } // 1/e
		static constexpr double invLn2() noexcept { return 0x1.71547652b82fep+0; } // 1/ln2
		static constexpr double invLn10() noexcept { return 0x1.bcb7b1526e50ep-2; } // 1/ln10

		// Angle
		static constexpr double degToRad() noexcept { return 0x1.1df46a2529d39p-6; } // pi/180
		static constexpr double radToDeg() noexcept { return 0x1.ca5dc1a63c1f8p+5; } // 180/pi

		// Special
		static constexpr double eulerMascheroni() noexcept { return 0x1.2788cfc6fb619p-1; } // Euler-Mascheroni gamma
		static constexpr double catalan() noexcept { return 0x1.d4f9713e8135dp-1; } // Catalan's constant G
		static constexpr double apery() noexcept { return 0x1.33ba004f00621p+0; } // Apery's constant zeta(3)
	};

	// Float128 (f128, 112-bit mantissa)

	template<>
	struct MathConstants<Float128> final {
		// Core
		// pi: 0x1.921fb54442d18469898cc51701b8p+1
		static constexpr double pi() noexcept { return /* TODO */ 0.0; }
		// 2*pi: 0x1.921fb54442d18469898cc51701b8p+2
		static constexpr double tau() noexcept { return /* TODO */ 0.0; }
		// Euler's number e: 0x1.5bf0a8b1457695355fb8ac404e7ap+1
		static constexpr double euler() noexcept { return /* TODO */ 0.0; }
		// sqrt(2): 0x1.6a09e667f3bcc908b2fb1366ea95p+0
		static constexpr double sqrt2() noexcept { return /* TODO */ 0.0; }
		// sqrt(3): 0x1.bb67ae8584caa73b25742d7078b8p+0
		static constexpr double sqrt3() noexcept { return /* TODO */ 0.0; }
		// sqrt(5): 0x1.1e3779b97f4a7c15f39cc0605ceep+1
		static constexpr double sqrt5() noexcept { return /* TODO */ 0.0; }
		// (1+sqrt(5))/2: 0x1.9e3779b97f4a7c15f39cc0605ceep+0
		static constexpr double goldenRatio() noexcept { return /* TODO */ 0.0; }

		// Logarithmic
		// log_e(2): 0x1.62e42fefa39ef35793c7673007e6p-1
		static constexpr double ln2() noexcept { return /* TODO */ 0.0; }
		// log_e(10): 0x1.26bb1bbb5551582dd4adac5705a6p+1
		static constexpr double ln10() noexcept { return /* TODO */ 0.0; }
		// log_2(e) = 1/ln2: 0x1.71547652b82fe1777d0ffda0d23ap+0
		static constexpr double log2e() noexcept { return /* TODO */ 0.0; }
		// log_10(e) = 1/ln10: 0x1.bcb7b1526e50e32a6ab7555f5a68p-2
		static constexpr double log10e() noexcept { return /* TODO */ 0.0; }
		// log_2(10): 0x1.a934f0979a3715fc9257edfe9b6p+1
		static constexpr double log2_10() noexcept { return /* TODO */ 0.0; }
		// log_10(2): 0x1.34413509f79fef311f12b35816f9p-2
		static constexpr double log10_2() noexcept { return /* TODO */ 0.0; }

		// Inverses
		// 1/pi: 0x1.45f306dc9c882a53f84eafa3ea6ap-2
		static constexpr double invPi() noexcept { return /* TODO */ 0.0; }
		// 1/(2*pi): 0x1.45f306dc9c882a53f84eafa3ea6ap-3
		static constexpr double invTwoPi() noexcept { return /* TODO */ 0.0; }
		// 1/e: 0x1.78b56362cef37c6aeb7b1e0a4154p-2
		static constexpr double invE() noexcept { return /* TODO */ 0.0; }
		// 1/ln2: 0x1.71547652b82fe1777d0ffda0d23ap+0
		static constexpr double invLn2() noexcept { return /* TODO */ 0.0; }
		// 1/ln10: 0x1.bcb7b1526e50e32a6ab7555f5a68p-2
		static constexpr double invLn10() noexcept { return /* TODO */ 0.0; }

		// Angle
		// pi/180: 0x1.1df46a2529d3915c1d8becdd290cp-6
		static constexpr double degToRad() noexcept { return /* TODO */ 0.0; }
		// 180/pi: 0x1.ca5dc1a63c1f7b86152ea6fe81a5p+5
		static constexpr double radToDeg() noexcept { return /* TODO */ 0.0; }

		// Special
		// Euler-Mascheroni gamma: 0x1.2788cfc6fb618f49a37c7f0202a6p-1
		static constexpr double eulerMascheroni() noexcept { return /* TODO */ 0.0; }
		// Catalan's constant G: 0x1.d4f9713e8135d08a42b045c6fa66p-1
		static constexpr double catalan() noexcept { return /* TODO */ 0.0; }
		// Apery's constant zeta(3): 0x1.33ba004f0062138371715c59e69p+0
		static constexpr double apery() noexcept { return /* TODO */ 0.0; }
	};

	//
	// Float256 (f256, 232-bit mantissa)
	//
	template<>
	struct MathConstants<Float256> final {
		// Core
		// pi: 0x1.921fb54442d18469898cc51701b839a252049c1114cf98e804177d4c76p+1
		static constexpr double pi() noexcept { return /* TODO */ 0.0; }
		// 2*pi: 0x1.921fb54442d18469898cc51701b839a252049c1114cf98e804177d4c76p+2
		static constexpr double tau() noexcept { return /* TODO */ 0.0; }
		// Euler's number e: 0x1.5bf0a8b1457695355fb8ac404e7a79e3b1738b079c5a6d2b53c26c8229p+1
		static constexpr double euler() noexcept { return /* TODO */ 0.0; }
		// sqrt(2): 0x1.6a09e667f3bcc908b2fb1366ea957d3e3adec17512775099da2f590b06p+0
		static constexpr double sqrt2() noexcept { return /* TODO */ 0.0; }
		// sqrt(3): 0x1.bb67ae8584caa73b25742d7078b83b8925d834cc53da4798c720a6486ep+0
		static constexpr double sqrt3() noexcept { return /* TODO */ 0.0; }
		// sqrt(5): 0x1.1e3779b97f4a7c15f39cc0605cedc8341082276bf3a27251f86c6a11d1p+1
		static constexpr double sqrt5() noexcept { return /* TODO */ 0.0; }
		// (1+sqrt(5))/2: 0x1.9e3779b97f4a7c15f39cc0605cedc8341082276bf3a27251f86c6a11d1p+0
		static constexpr double goldenRatio() noexcept { return /* TODO */ 0.0; }

		// Logarithmic
		// log_e(2): 0x1.62e42fefa39ef35793c7673007e5ed5e81e6864ce5316c5b141a2eb717p-1
		static constexpr double ln2() noexcept { return /* TODO */ 0.0; }
		// log_e(10): 0x1.26bb1bbb5551582dd4adac5705a61451c51fd9f3b4bbf21d078c3d0404p+1
		static constexpr double ln10() noexcept { return /* TODO */ 0.0; }
		// log_2(e) = 1/ln2: 0x1.71547652b82fe1777d0ffda0d23a7d11d6aef551bad2b4b1164a2cd9a3p+0
		static constexpr double log2e() noexcept { return /* TODO */ 0.0; }
		// log_10(e) = 1/ln10: 0x1.bcb7b1526e50e32a6ab7555f5a67b8647dc68c048b934404747e5a89efp-2
		static constexpr double log10e() noexcept { return /* TODO */ 0.0; }
		// log_2(10): 0x1.a934f0979a3715fc9257edfe9b5fb699b2d8abfc6f675a9d236d590106p+1
		static constexpr double log2_10() noexcept { return /* TODO */ 0.0; }
		// log_10(2): 0x1.34413509f79fef311f12b35816f922f04d5a618a87a3e69314bcde4d7p-2
		static constexpr double log10_2() noexcept { return /* TODO */ 0.0; }

		// Inverses
		// 1/pi: 0x1.45f306dc9c882a53f84eafa3ea69bb81b6c52b3278872083fca2c757bdp-2
		static constexpr double invPi() noexcept { return /* TODO */ 0.0; }
		// 1/(2*pi): 0x1.45f306dc9c882a53f84eafa3ea69bb81b6c52b3278872083fca2c757bdp-3
		static constexpr double invTwoPi() noexcept { return /* TODO */ 0.0; }
		// 1/e: 0x1.78b56362cef37c6aeb7b1e0a4153e4376a6016aad5b1dcccc092e74294p-2
		static constexpr double invE() noexcept { return /* TODO */ 0.0; }
		// 1/ln2: 0x1.71547652b82fe1777d0ffda0d23a7d11d6aef551bad2b4b1164a2cd9a3p+0
		static constexpr double invLn2() noexcept { return /* TODO */ 0.0; }
		// 1/ln10: 0x1.bcb7b1526e50e32a6ab7555f5a67b8647dc68c048b934404747e5a89efp-2
		static constexpr double invLn10() noexcept { return /* TODO */ 0.0; }

		// Angle
		// pi/180: 0x1.1df46a2529d3915c1d8becdd290b89b2016f5dea036bcd71ca05536993p-6
		static constexpr double degToRad() noexcept { return /* TODO */ 0.0; }
		// 180/pi: 0x1.ca5dc1a63c1f7b86152ea6fe81a4afae690544bef97e05b99b44e85362p+5
		static constexpr double radToDeg() noexcept { return /* TODO */ 0.0; }

		// Special
		// Euler-Mascheroni gamma: 0x1.2788cfc6fb618f49a37c7f0202a596ad439d9875ecb980321807be68e1p-1
		static constexpr double eulerMascheroni() noexcept { return /* TODO */ 0.0; }
		// Catalan's constant G: 0x1.d4f9713e8135d08a42b045c6fa65a18c7d887c270385ff012944c7cb48p-1
		static constexpr double catalan() noexcept { return /* TODO */ 0.0; }
		// Apery's constant zeta(3): 0x1.33ba004f0062138371715c59e6907f1b180b7db17493405dd149c7ab13p+0
		static constexpr double apery() noexcept { return /* TODO */ 0.0; }
	};

	//
	// Float512 (f512, 479-bit mantissa)
	//
	template<>
	struct MathConstants<Float512> final {
		// Core
		// pi: 0x1.921fb54442d18469898cc51701b839a252049c1114cf98e804177d4c76273644a29410f31c6809bbdf2a33679a748636605614dbe4be286e9fc26adap+1
		static constexpr double pi() noexcept { return /* TODO */ 0.0; }
		// 2*pi: 0x1.921fb54442d18469898cc51701b839a252049c1114cf98e804177d4c76273644a29410f31c6809bbdf2a33679a748636605614dbe4be286e9fc26adap+2
		static constexpr double tau() noexcept { return /* TODO */ 0.0; }
		// Euler's number e: 0x1.5bf0a8b1457695355fb8ac404e7a79e3b1738b079c5a6d2b53c26c8228c867f799273b9c49367df2fa5fc6c6c618ebb1ed0364055d88c2f5a7be3dacp+1
		static constexpr double euler() noexcept { return /* TODO */ 0.0; }
		// sqrt(2): 0x1.6a09e667f3bcc908b2fb1366ea957d3e3adec17512775099da2f590b0667322a95f90608757145875163fcdfb907b6721ee950bc8738f694f0090e6cp+0
		static constexpr double sqrt2() noexcept { return /* TODO */ 0.0; }
		// sqrt(3): 0x1.bb67ae8584caa73b25742d7078b83b8925d834cc53da4798c720a6486e45a6e2490bcfd95ef15dbda9930aae12228f87cc4cf24da3a1ec68d0cd33ap+0
		static constexpr double sqrt3() noexcept { return /* TODO */ 0.0; }
		// sqrt(5): 0x1.1e3779b97f4a7c15f39cc0605cedc8341082276bf3a27251f86c6a11d0c18e952767f0b153d27b7f0347045b5bf1827f01886f0928403002c1d64ba4p+1
		static constexpr double sqrt5() noexcept { return /* TODO */ 0.0; }
		// (1+sqrt(5))/2: 0x1.9e3779b97f4a7c15f39cc0605cedc8341082276bf3a27251f86c6a11d0c18e952767f0b153d27b7f0347045b5bf1827f01886f0928403002c1d64ba4p+0
		static constexpr double goldenRatio() noexcept { return /* TODO */ 0.0; }

		// Logarithmic
		// log_e(2): 0x1.62e42fefa39ef35793c7673007e5ed5e81e6864ce5316c5b141a2eb71755f457cf70ec40dbd75930ab2aa5f695f43621da5d5c6b827042884eae7652p-1
		static constexpr double ln2() noexcept { return /* TODO */ 0.0; }
		// log_e(10): 0x1.26bb1bbb5551582dd4adac5705a61451c51fd9f3b4bbf21d078c3d0403e05ae52c5e05af635020b998e1978058be1ad058c448308217c5b5f71ef108p+1
		static constexpr double ln10() noexcept { return /* TODO */ 0.0; }
		// log_2(e) = 1/ln2: 0x1.71547652b82fe1777d0ffda0d23a7d11d6aef551bad2b4b1164a2cd9a342648fbc3887eeaa2ed9ac49b25eeb82d7c167d52173cc1895213f897f5e06p+0
		static constexpr double log2e() noexcept { return /* TODO */ 0.0; }
		// log_10(e) = 1/ln10: 0x1.bcb7b1526e50e32a6ab7555f5a67b8647dc68c048b934404747e5a89ef1d4a78ea849df42805e7e52446ab258c8c942a319c77b3fa71b978df4571a6p-2
		static constexpr double log10e() noexcept { return /* TODO */ 0.0; }
		// log_2(10): 0x1.a934f0979a3715fc9257edfe9b5fb699b2d8abfc6f675a9d236d590105cf0b3a0cca1fbd3baa3e747c497d56c75a17ac286bdc900acb94a99fe2c59ap+1
		static constexpr double log2_10() noexcept { return /* TODO */ 0.0; }
		// log_10(2): 0x1.34413509f79fef311f12b35816f922f04d5a618a87a3e69314bcde4d6f98c79650d45b03233f57a13cb978e668e37a25228e692b6317243cb16a4feap-2
		static constexpr double log10_2() noexcept { return /* TODO */ 0.0; }

		// Inverses
		// 1/pi: 0x1.45f306dc9c882a53f84eafa3ea69bb81b6c52b3278872083fca2c757bd778ac36e48dc74849ba5c00c925dd413a32439fc3bd63962534e7dd1046beap-2
		static constexpr double invPi() noexcept { return /* TODO */ 0.0; }
		// 1/(2*pi): 0x1.45f306dc9c882a53f84eafa3ea69bb81b6c52b3278872083fca2c757bd778ac36e48dc74849ba5c00c925dd413a32439fc3bd63962534e7dd1046beap-3
		static constexpr double invTwoPi() noexcept { return /* TODO */ 0.0; }
		// 1/e: 0x1.78b56362cef37c6aeb7b1e0a4153e4376a6016aad5b1dcccc092e742941f6bb6c59002fd1cad0856e0916d9a764349e96ba955425a370e48a7c0f18ap-2
		static constexpr double invE() noexcept { return /* TODO */ 0.0; }
		// 1/ln2: 0x1.71547652b82fe1777d0ffda0d23a7d11d6aef551bad2b4b1164a2cd9a342648fbc3887eeaa2ed9ac49b25eeb82d7c167d52173cc1895213f897f5e06p+0
		static constexpr double invLn2() noexcept { return /* TODO */ 0.0; }
		// 1/ln10: 0x1.bcb7b1526e50e32a6ab7555f5a67b8647dc68c048b934404747e5a89ef1d4a78ea849df42805e7e52446ab258c8c942a319c77b3fa71b978df4571a6p-2
		static constexpr double invLn10() noexcept { return /* TODO */ 0.0; }

		// Angle
		// pi/180: 0x1.1df46a2529d3915c1d8becdd290b89b2016f5dea036bcd71ca05536992990a256dec22cf0322290e218a192d3aa28192c1a94d692b31e3dce3626e1ep-6
		static constexpr double degToRad() noexcept { return /* TODO */ 0.0; }
		// 180/pi: 0x1.ca5dc1a63c1f7b86152ea6fe81a4afae690544bef97e05b99b44e85362701b22d3167603da7ae11611add3f23b9d6af18ab42540b2452660edee37c2p+5
		static constexpr double radToDeg() noexcept { return /* TODO */ 0.0; }

		// Special
		// Euler-Mascheroni gamma: 0x1.2788cfc6fb618f49a37c7f0202a596ad439d9875ecb980321807be68e135ff7b1c96b3f40753e1dda0c93996c420afa220ad5d226426b411c8768ce8p-1
		static constexpr double eulerMascheroni() noexcept { return /* TODO */ 0.0; }
		// Catalan's constant G: 0x1.d4f9713e8135d08a42b045c6fa65a18c7d887c270385ff012944c7cb4799aedf29b80b148ddd8b0b1f249acc7ee73885d92bf1b425e2d7f8b176419p-1
		static constexpr double catalan() noexcept { return /* TODO */ 0.0; }
		// Apery's constant zeta(3): 0x1.33ba004f0062138371715c59e6907f1b180b7db17493405dd149c7ab12d7f6b8d04e653afb2ce61e94a06c300998821917556a352a65193f75c783fp+0
		static constexpr double apery() noexcept { return /* TODO */ 0.0; }
	};

	//
	// Float1024 (f1024, 991-bit mantissa)
	//
	template<>
	struct MathConstants<Float1024> final {
		// Core
		// pi: 0x1.921fb54442d18469898cc51701b839a252049c1114cf98e804177d4c76273644a29410f31c6809bbdf2a33679a748636605614dbe4be286e9fc26adadaa3848bc90b6aecc4bcfd8de89885d34c6fdad617feb96de80d6fdbdc70d7f6b5133f4b5d3e4822f8963fcc9250cca3d9c8b67b8400f97142c77e0b31b4906cp+1
		static constexpr double pi() noexcept { return /* TODO */ 0.0; }
		// 2*pi: 0x1.921fb54442d18469898cc51701b839a252049c1114cf98e804177d4c76273644a29410f31c6809bbdf2a33679a748636605614dbe4be286e9fc26adadaa3848bc90b6aecc4bcfd8de89885d34c6fdad617feb96de80d6fdbdc70d7f6b5133f4b5d3e4822f8963fcc9250cca3d9c8b67b8400f97142c77e0b31b4906cp+2
		static constexpr double tau() noexcept { return /* TODO */ 0.0; }
		// Euler's number e: 0x1.5bf0a8b1457695355fb8ac404e7a79e3b1738b079c5a6d2b53c26c8228c867f799273b9c49367df2fa5fc6c6c618ebb1ed0364055d88c2f5a7be3dababfacac24867ea3ebe0cdda10ac6caaa7bda35e76aae26bcfeaf926b309e18e1c1cd16efc54d13b5e7dfd0e43be2b1426d5bce6a6159949e9074f2f578156306p+1
		static constexpr double euler() noexcept { return /* TODO */ 0.0; }
		// sqrt(2): 0x1.6a09e667f3bcc908b2fb1366ea957d3e3adec17512775099da2f590b0667322a95f90608757145875163fcdfb907b6721ee950bc8738f694f0090e6c7bf44ed1a4405d0e855e3e9ca60b38c0237866f7956379222d108b148c1578e45ef89c678dab5147176fd3b99654c68663e7909bea5e241f06dcb05dd5494114p+0
		static constexpr double sqrt2() noexcept { return /* TODO */ 0.0; }
		// sqrt(3): 0x1.bb67ae8584caa73b25742d7078b83b8925d834cc53da4798c720a6486e45a6e2490bcfd95ef15dbda9930aae12228f87cc4cf24da3a1ec68d0cd33a01ad9a383b9e122e6138c3ae6de5ede3bd42db7301b6bf553af7b09fd6ebef33a9a9fe57729426f30e5892ab572816ccefc5899355f7f11c3e24f3768a5c7cb9p+0
		static constexpr double sqrt3() noexcept { return /* TODO */ 0.0; }
		// sqrt(5): 0x1.1e3779b97f4a7c15f39cc0605cedc8341082276bf3a27251f86c6a11d0c18e952767f0b153d27b7f0347045b5bf1827f01886f0928403002c1d64ba40f335e36f06ad7ae9717877e85839d6effbd7dc664d325d1c5371682cadd0cccfdffbbe1626e33b8d04b4331bbf73c790d94f79d471c4ab3ed3d82a5fec5077p+1
		static constexpr double sqrt5() noexcept { return /* TODO */ 0.0; }
		// (1+sqrt(5))/2: 0x1.9e3779b97f4a7c15f39cc0605cedc8341082276bf3a27251f86c6a11d0c18e952767f0b153d27b7f0347045b5bf1827f01886f0928403002c1d64ba40f335e36f06ad7ae9717877e85839d6effbd7dc664d325d1c5371682cadd0cccfdffbbe1626e33b8d04b4331bbf73c790d94f79d471c4ab3ed3d82a5fec5077p+0
		static constexpr double goldenRatio() noexcept { return /* TODO */ 0.0; }

		// Logarithmic
		// log_e(2): 0x1.62e42fefa39ef35793c7673007e5ed5e81e6864ce5316c5b141a2eb71755f457cf70ec40dbd75930ab2aa5f695f43621da5d5c6b827042884eae765222d3704a7d2d942c4495d18a3597b42262f870fd73d53787626cc0764adf41d8ecafee96e59d0f633aca9195ebbf4d7a70606490cabf430e5e41c745b45b2f8ap-1
		static constexpr double ln2() noexcept { return /* TODO */ 0.0; }
		// log_e(10): 0x1.26bb1bbb5551582dd4adac5705a61451c51fd9f3b4bbf21d078c3d0403e05ae52c5e05af635020b998e1978058be1ad058c448308217c5b5f71ef10805ca2dacf059f1451519223cecb54d8761b063f7decd9d6095678df4a2c37693a4338f7794cf66b646c0a10b1d266d1a88f1389eb61160afabdbc41e8d3d4b1ep+1
		static constexpr double ln10() noexcept { return /* TODO */ 0.0; }
		// log_2(e) = 1/ln2: 0x1.71547652b82fe1777d0ffda0d23a7d11d6aef551bad2b4b1164a2cd9a342648fbc3887eeaa2ed9ac49b25eeb82d7c167d52173cc1895213f897f5e06a7be73665fc529264c2fb3ab643687aaf3ab440c16bd777e75050a8d1a39e8af56c64a7833352906deb692ce4f199e108cf392819cfc406b19abb71ec25e11f8p+0
		static constexpr double log2e() noexcept { return /* TODO */ 0.0; }
		// log_10(e) = 1/ln10: 0x1.bcb7b1526e50e32a6ab7555f5a67b8647dc68c048b934404747e5a89ef1d4a78ea849df42805e7e52446ab258c8c942a319c77b3fa71b978df4571a5919b4f6686ad7a3291a0dff2800e400b183b89b4cb16c3d485909ad4a166dbda5e6e73aaa8604255cd1809a8c91d991398a3f269af29ac9e4f92d1d767fc8186p-2
		static constexpr double log10e() noexcept { return /* TODO */ 0.0; }
		// log_2(10): 0x1.a934f0979a3715fc9257edfe9b5fb699b2d8abfc6f675a9d236d590105cf0b3a0cca1fbd3baa3e747c497d56c75a17ac286bdc900acb94a99fe2c59a9ec06703ec9f2d82fb36ba9bfdcd84d71f1937a070bcbf203985a3591d1eeaeea212a6170cb18dbfd47ddae2609f11687d6570df5526c79f38331189ad389784p+1
		static constexpr double log2_10() noexcept { return /* TODO */ 0.0; }
		// log_10(2): 0x1.34413509f79fef311f12b35816f922f04d5a618a87a3e69314bcde4d6f98c79650d45b03233f57a13cb978e668e37a25228e692b6317243cb16a4fea4aa5a598bf06fbdc04aab97939e3a321880c05cba4d84e5fbce205e9d72225362b25b3b8091afd4b3d62a7b01610678b28357042d46cf70279e991f7bdd462fp-2
		static constexpr double log10_2() noexcept { return /* TODO */ 0.0; }

		// Inverses
		// 1/pi: 0x1.45f306dc9c882a53f84eafa3ea69bb81b6c52b3278872083fca2c757bd778ac36e48dc74849ba5c00c925dd413a32439fc3bd63962534e7dd1046bea5d768909d338e04d68befc827323ac7306a673e93908bf177bf250763ff12fffbc0b301fde5e2316b414da3eda6cfd9e4f96136e9e8c7ecd3cbfd45aea4f759p-2
		static constexpr double invPi() noexcept { return /* TODO */ 0.0; }
		// 1/(2*pi): 0x1.45f306dc9c882a53f84eafa3ea69bb81b6c52b3278872083fca2c757bd778ac36e48dc74849ba5c00c925dd413a32439fc3bd63962534e7dd1046bea5d768909d338e04d68befc827323ac7306a673e93908bf177bf250763ff12fffbc0b301fde5e2316b414da3eda6cfd9e4f96136e9e8c7ecd3cbfd45aea4f759p-3
		static constexpr double invTwoPi() noexcept { return /* TODO */ 0.0; }
		// 1/e: 0x1.78b56362cef37c6aeb7b1e0a4153e4376a6016aad5b1dcccc092e742941f6bb6c59002fd1cad0856e0916d9a764349e96ba955425a370e48a7c0f189db72a96303b0acef6eaa49c36497f6f56033c537021f0fcff911189b34ab79396344490d9ea06fa8dd93b53df75706e364313bdf5b76462347255a968ef95734p-2
		static constexpr double invE() noexcept { return /* TODO */ 0.0; }
		// 1/ln2: 0x1.71547652b82fe1777d0ffda0d23a7d11d6aef551bad2b4b1164a2cd9a342648fbc3887eeaa2ed9ac49b25eeb82d7c167d52173cc1895213f897f5e06a7be73665fc529264c2fb3ab643687aaf3ab440c16bd777e75050a8d1a39e8af56c64a7833352906deb692ce4f199e108cf392819cfc406b19abb71ec25e11f8p+0
		static constexpr double invLn2() noexcept { return /* TODO */ 0.0; }
		// 1/ln10: 0x1.bcb7b1526e50e32a6ab7555f5a67b8647dc68c048b934404747e5a89ef1d4a78ea849df42805e7e52446ab258c8c942a319c77b3fa71b978df4571a5919b4f6686ad7a3291a0dff2800e400b183b89b4cb16c3d485909ad4a166dbda5e6e73aaa8604255cd1809a8c91d991398a3f269af29ac9e4f92d1d767fc8186p-2
		static constexpr double invLn10() noexcept { return /* TODO */ 0.0; }

		// Angle
		// pi/180: 0x1.1df46a2529d3915c1d8becdd290b89b2016f5dea036bcd71ca05536992990a256dec22cf0322290e218a192d3aa28192c1a94d692b31e3dce3626e1e7957d5b8bc79e5a2ae093cd6b0c77b9bf216a6fea4f9676a99a327b8ca44ddd7422fd1fcb41588a166d13e6f56fae12a8f7da996693f454ada277613568bc76ap-6
		static constexpr double degToRad() noexcept { return /* TODO */ 0.0; }
		// 180/pi: 0x1.ca5dc1a63c1f7b86152ea6fe81a4afae690544bef97e05b99b44e85362701b22d3167603da7ae11611add3f23b9d6af18ab42540b2452660edee37c1936eb0b5d107fb6cdb4c931771ea2a81c15a12fff8344cb9064cc12649eb2b7fa06fbbacd0b46157ed3d52e8632944a69feb0b538ef592509d6dc29fd97fbd52p+5
		static constexpr double radToDeg() noexcept { return /* TODO */ 0.0; }

		// Special
		// Euler-Mascheroni gamma: 0x1.2788cfc6fb618f49a37c7f0202a596ad439d9875ecb980321807be68e135ff7b1c96b3f40753e1dda0c93996c420afa220ad5d226426b411c8768ce7ae975fd4b1bd70f1990dae67b7cf7e702a966d9f152da2acf133555c1813a9916d6f70dfa543d43bcc5ff0c87d8f84e304f2ee44bcd585e17ac38e8d2c2a8548p-1
		static constexpr double eulerMascheroni() noexcept { return /* TODO */ 0.0; }
		// Catalan's constant G: 0x1.d4f9713e8135d08a42b045c6fa65a18c7d887c270385ff012944c7cb4799aedf29b80b148ddd8b0b1f249acc7ee73885d92bf1b425e2d7f8b176418fe40c74d8dedbca019729e6b19fbd908570a3eef7b44aa5059c124142ffe9fe8ce71f1cb4f8dcd131eb40305a86eb34ead01a038d186f000a276751baeccd35f2p-1
		static constexpr double catalan() noexcept { return /* TODO */ 0.0; }
		// Apery's constant zeta(3): 0x1.33ba004f0062138371715c59e6907f1b180b7db17493405dd149c7ab12d7f6b8d04e653afb2ce61e94a06c300998821917556a352a65193f75c783f0c7a8bc2ed00d6c2b64aa702dcc359617f1feb0efa4ba636e66a29213b6cdcda294963778de6e99e6f9d5d3f0df49f4a690221131afcf79353b7bb3cadba7ece8p+0
		static constexpr double apery() noexcept { return /* TODO */ 0.0; }
	};
} // namespace Leibniz::Numerics::Constants