// AUTO-GENERATED by striped_tables_gen.py - DO NOT EDIT BY HAND
// Leibniz HPC Math Library - AVX2 Pre-Broadcast Stripe Tables
//
// Purpose:
//   Provides lazy-static __m256 / __m256d broadcast registers for every
//   LookUpTables.h coefficient, eliminating scalar load + broadcast from
//   Horner evaluation hot paths.
//
// Tiers included:
//   Balanced    - Chebyshev minimax, ~N/2 terms
//   Approximate - Chebyshev minimax, ~N/3 terms
//   Exact tier is intentionally excluded (register pressure)
//
// Types:
//   FP32  - __m256  (8 x float,  AVX2)
//   FP64  - __m256d (4 x double, AVX2)
//
// Usage pattern (Horner kernel):
//   Leibniz::Numerics::Vectorized::StripedTables::FP32::Balanced::Exp tbl;
//   __m256 acc = tbl.c3();
//   acc = _mm256_fmadd_ps(acc, x, tbl.c2());
//   acc = _mm256_fmadd_ps(acc, x, tbl.c1());
//   acc = _mm256_fmadd_ps(acc, x, tbl.c0());
//
// Evaluation conventions (inherited from LookUpTables.h):
//   Straight  (Exp, Log*, Expm1, Exp2, Exp10, Acosh):  Horner(x, c)
//   Odd       (Sin, Tan, Asin, Atan, Sinh, Asinh, Atanh, Erf): x * Horner(x^2, c)
//   Even      (Cos, Cosh):                              Horner(x^2, c)
//   Seeds     (SqrtSeed, RsqrtSeed, CbrtSeed):          seed + Newton-Raphson
//   Lanczos   (lgamma/tgamma):                          rational sum g=7, 9-term
//   ErfcAsymptotic: (exp(-x^2) / (x * sqrt(pi))) * Horner(1/x^2, c)
//
// Functions without tables (share stripe registers from above):
//   ACOS      acos(x)  = pi/2 - asin(x)          - reuses Asin stripes
//   ATAN2     atan2(y,x) = atan + quadrant fix     - reuses Atan stripes
//   TANH      tanh(x)  = sinh(x)/cosh(x)          - reuses Sinh, Cosh stripes
//   POW       pow(x,y) = exp(y*log(x))            - reuses Exp, Log1p stripes
//   HYPOT     hypot(a,b) = sqrt(a^2+b^2)          - reuses SqrtSeed stripes
//   SIGMOID   sigmoid(x) = 1/(1+exp(-x))          - reuses Exp stripes
//   SOFTPLUS  softplus(x) = log(1+exp(x))         - reuses Exp, Log1p stripes
//   LGAMMA    lgamma/tgamma share Lanczos stripes
//
// Namespace structure:
//   Leibniz::Numerics::Vectorized::StripedTables::FP32::{Balanced,Approximate}::{Struct}
//   Leibniz::Numerics::Vectorized::StripedTables::FP64::{Balanced,Approximate}::{Struct}
//
// Accessor pattern (lazy static, initialized once on first call):
//   inline const __m256&  cN() { static const __m256  v = _mm256_set1_ps(...); return v; }
//   inline const __m256d& cN() { static const __m256d v = _mm256_set1_pd(...); return v; }
#pragma once
#include <immintrin.h>

namespace Leibniz::Numerics::Vectorized {
	namespace FP32 {
		namespace Balanced {
			struct LEIBNIZ_RUNTIME_API Exp final {
				Exp() = delete;
				~Exp() = delete;
				Exp(const Exp&) = delete;
				Exp(Exp&&) = delete;
				Exp& operator=(const Exp&) = delete;
				Exp& operator=(Exp&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.fff61cp-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.fffe06p-1f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.029248p-1f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.57636ep-3f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Expm1 final {
				Expm1() = delete;
				~Expm1() = delete;
				Expm1(const Expm1&) = delete;
				Expm1(Expm1&&) = delete;
				Expm1& operator=(const Expm1&) = delete;
				Expm1& operator=(Expm1&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.fffe06p-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.ffff58p-2f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.57636ep-3f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.56b3d8p-5f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Exp2 final {
				Exp2() = delete;
				~Exp2() = delete;
				Exp2(const Exp2&) = delete;
				Exp2(Exp2&&) = delete;
				Exp2& operator=(const Exp2&) = delete;
				Exp2& operator=(Exp2&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.fffdb8p-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.62e3ep-1f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.ee5a96p-3f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.c800d2p-5f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Exp10 final {
				Exp10() = delete;
				~Exp10() = delete;
				Exp10(const Exp10&) = delete;
				Exp10(Exp10&&) = delete;
				Exp10& operator=(const Exp10&) = delete;
				Exp10& operator=(Exp10&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.fee536p-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.269acp+1f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.65aaacp+1f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.0cd7acp+1f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Log1p final {
				Log1p() = delete;
				~Log1p() = delete;
				Log1p(const Log1p&) = delete;
				Log1p(Log1p&&) = delete;
				Log1p& operator=(const Log1p&) = delete;
				Log1p& operator=(Log1p&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(-0x1.5ap-109f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.fd7234p-1f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(-0x1.fbb0fp-2f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.a35456p-2f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(-0x1.41a74ap-2f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Log2 final {
				Log2() = delete;
				~Log2() = delete;
				Log2(const Log2&) = delete;
				Log2(Log2&&) = delete;
				Log2& operator=(const Log2&) = delete;
				Log2& operator=(Log2&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(-0x1.0p-108f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.6f7cd8p+0f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(-0x1.6e38c6p-1f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.2e7b74p-1f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(-0x1.d00c42p-2f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Log10 final {
				Log10() = delete;
				~Log10() = delete;
				Log10(const Log10&) = delete;
				Log10(Log10&&) = delete;
				Log10& operator=(const Log10&) = delete;
				Log10& operator=(Log10&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(-0x1.76p-110f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.ba7fdp-2f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(-0x1.b8f996p-3f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.6c3994p-3f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(-0x1.17627ap-3f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Sin final {
				Sin() = delete;
				~Sin() = delete;
				Sin(const Sin&) = delete;
				Sin(Sin&&) = delete;
				Sin& operator=(const Sin&) = delete;
				Sin& operator=(Sin&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.1p-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.555556p-3f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.111112p-7f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(-0x1.a019f8p-13f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(0x1.71d732p-19f); return v; }
				static inline const __m256& c5() { static const __m256 v = _mm256_set1_ps(-0x1.a9508p-26f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Cos final {
				Cos() = delete;
				~Cos() = delete;
				Cos(const Cos&) = delete;
				Cos(Cos&&) = delete;
				Cos& operator=(const Cos&) = delete;
				Cos& operator=(Cos&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.1p-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.1p-2f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.555556p-5f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(-0x1.6c16b2p-10f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(0x1.a00e96p-16f); return v; }
				static inline const __m256& c5() { static const __m256 v = _mm256_set1_ps(-0x1.23c5c2p-22f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Tan final {
				Tan() = delete;
				~Tan() = delete;
				Tan(const Tan&) = delete;
				Tan(Tan&&) = delete;
				Tan& operator=(const Tan&) = delete;
				Tan& operator=(Tan&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.fffff8p-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.555c1ap-2f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.10158ep-3f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.d44a86p-5f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(0x1.9bb3ccp-7f); return v; }
				static inline const __m256& c5() { static const __m256 v = _mm256_set1_ps(0x1.4db42ap-6f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Asin final {
				Asin() = delete;
				~Asin() = delete;
				Asin(const Asin&) = delete;
				Asin(Asin&&) = delete;
				Asin& operator=(const Asin&) = delete;
				Asin& operator=(Asin&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.000002p+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.554dcp-3f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.350eaep-4f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.45ffp-5f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(0x1.9c87b6p-5f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Atan final {
				Atan() = delete;
				~Atan() = delete;
				Atan(const Atan&) = delete;
				Atan(Atan&&) = delete;
				Atan& operator=(const Atan&) = delete;
				Atan& operator=(Atan&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.ffff52p-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.54f2b6p-2f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.9011ep-3f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(-0x1.ed5b7ep-4f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(0x1.cf95ccp-5f); return v; }
				static inline const __m256& c5() { static const __m256 v = _mm256_set1_ps(-0x1.ae41ap-7f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Sinh final {
				Sinh() = delete;
				~Sinh() = delete;
				Sinh(const Sinh&) = delete;
				Sinh(Sinh&&) = delete;
				Sinh& operator=(const Sinh&) = delete;
				Sinh& operator=(Sinh&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.1p-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.555556p-3f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.1110a6p-7f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.a17df2p-13f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Cosh final {
				Cosh() = delete;
				~Cosh() = delete;
				Cosh(const Cosh&) = delete;
				Cosh(Cosh&&) = delete;
				Cosh& operator=(const Cosh&) = delete;
				Cosh& operator=(Cosh&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.1p-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.0p-1f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.555464p-5f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.6da754p-10f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Asinh final {
				Asinh() = delete;
				~Asinh() = delete;
				Asinh(const Asinh&) = delete;
				Asinh(Asinh&&) = delete;
				Asinh& operator=(const Asinh&) = delete;
				Asinh& operator=(Asinh&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.fffffp-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.5539f8p-3f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.2f8124p-4f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(-0x1.3ef194p-5f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(0x1.ce028cp-7f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Acosh final {
				Acosh() = delete;
				~Acosh() = delete;
				Acosh(const Acosh&) = delete;
				Acosh(Acosh&&) = delete;
				Acosh& operator=(const Acosh&) = delete;
				Acosh& operator=(Acosh&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.6a09e6p+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.e2b3dp-4f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.b1697p-6f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(-0x1.ecfc96p-8f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(0x1.cc0298p-10f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Atanh final {
				Atanh() = delete;
				~Atanh() = delete;
				Atanh(const Atanh&) = delete;
				Atanh(Atanh&&) = delete;
				Atanh& operator=(const Atanh&) = delete;
				Atanh& operator=(Atanh&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.000006p+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.55452p-2f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.9d8f88p-3f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.f4c8aep-4f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(0x1.8fc48ap-3f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Erf final {
				Erf() = delete;
				~Erf() = delete;
				Erf(const Erf&) = delete;
				Erf(Erf&&) = delete;
				Erf& operator=(const Erf&) = delete;
				Erf& operator=(Erf&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.20dd74p+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.81268p-2f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.ce0ab2p-4f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(-0x1.b5b31p-6f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(0x1.428d76p-8f); return v; }
				static inline const __m256& c5() { static const __m256 v = _mm256_set1_ps(-0x1.281efap-11f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API ErfcAsymptotic final {
				ErfcAsymptotic() = delete;
				~ErfcAsymptotic() = delete;
				ErfcAsymptotic(const ErfcAsymptotic&) = delete;
				ErfcAsymptotic(ErfcAsymptotic&&) = delete;
				ErfcAsymptotic& operator=(const ErfcAsymptotic&) = delete;
				ErfcAsymptotic& operator=(ErfcAsymptotic&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.0p+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.0p-1f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.8p-1f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(-0x1.ep+0f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API SqrtSeed final {
				SqrtSeed() = delete;
				~SqrtSeed() = delete;
				SqrtSeed(const SqrtSeed&) = delete;
				SqrtSeed(SqrtSeed&&) = delete;
				SqrtSeed& operator=(const SqrtSeed&) = delete;
				SqrtSeed& operator=(SqrtSeed&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.669044p-3f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.433fa4p+0f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(-0x1.ac8a38p-1f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.df42c2p-2f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(-0x1.42c35ap-4f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API RsqrtSeed final {
				RsqrtSeed() = delete;
				~RsqrtSeed() = delete;
				RsqrtSeed(const RsqrtSeed&) = delete;
				RsqrtSeed(RsqrtSeed&&) = delete;
				RsqrtSeed& operator=(const RsqrtSeed&) = delete;
				RsqrtSeed& operator=(RsqrtSeed&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.c6b9cep+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.67cdcep+0f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.f3625ap-1f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(-0x1.7d02f2p-2f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(0x1.cd2876p-5f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API CbrtSeed final {
				CbrtSeed() = delete;
				~CbrtSeed() = delete;
				CbrtSeed(const CbrtSeed&) = delete;
				CbrtSeed(CbrtSeed&&) = delete;
				CbrtSeed& operator=(const CbrtSeed&) = delete;
				CbrtSeed& operator=(CbrtSeed&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.395abp-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.ba4fd4p-1f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(-0x1.23bd2cp-1f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.18e382p-2f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(-0x1.e2ee22p-5f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Lanczos final {
				Lanczos() = delete;
				~Lanczos() = delete;
				Lanczos(const Lanczos&) = delete;
				Lanczos(Lanczos&&) = delete;
				Lanczos& operator=(const Lanczos&) = delete;
				Lanczos& operator=(Lanczos&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.1p-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.52429cp+9f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(-0x1.3ac8e8p+10f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.81a966p+9f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(-0x1.613ae6p+7f); return v; }
				static inline const __m256& c5() { static const __m256 v = _mm256_set1_ps(0x1.903c28p+3f); return v; }
				static inline const __m256& c6() { static const __m256 v = _mm256_set1_ps(-0x1.1bcb2ap-3f); return v; }
				static inline const __m256& c7() { static const __m256 v = _mm256_set1_ps(0x1.4b045ap-17f); return v; }
				static inline const __m256& c8() { static const __m256 v = _mm256_set1_ps(0x1.433a1cp-23f); return v; }
			};
		} // namespace Balanced

		namespace Approximate {
			struct LEIBNIZ_RUNTIME_API Exp final {
				Exp() = delete;
				~Exp() = delete;
				Exp(const Exp&) = delete;
				Exp(Exp&&) = delete;
				Exp& operator=(const Exp&) = delete;
				Exp& operator=(Exp&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.0p+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.03dc68p+0f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.01ed76p-1f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Expm1 final {
				Expm1() = delete;
				~Expm1() = delete;
				Expm1(const Expm1&) = delete;
				Expm1(Expm1&&) = delete;
				Expm1& operator=(const Expm1&) = delete;
				Expm1& operator=(Expm1&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.0p+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.01ed76p-1f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.56dfc4p-3f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Exp2 final {
				Exp2() = delete;
				~Exp2() = delete;
				Exp2(const Exp2&) = delete;
				Exp2(Exp2&&) = delete;
				Exp2& operator=(const Exp2&) = delete;
				Exp2& operator=(Exp2&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.0p+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.6574fap-1f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.edc2ccp-3f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Exp10 final {
				Exp10() = delete;
				~Exp10() = delete;
				Exp10(const Exp10&) = delete;
				Exp10(Exp10&&) = delete;
				Exp10& operator=(const Exp10&) = delete;
				Exp10& operator=(Exp10&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.0p+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.3ec25cp+1f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.610b4p+1f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Log1p final {
				Log1p() = delete;
				~Log1p() = delete;
				Log1p(const Log1p&) = delete;
				Log1p(Log1p&&) = delete;
				Log1p& operator=(const Log1p&) = delete;
				Log1p& operator=(Log1p&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(-0x1.0p-109f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.121528p+0f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(-0x1.1b7f38p-1f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Log2 final {
				Log2() = delete;
				~Log2() = delete;
				Log2(const Log2&) = delete;
				Log2(Log2&&) = delete;
				Log2& operator=(const Log2&) = delete;
				Log2& operator=(Log2&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(-0x1.4p-109f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.8b6aecp+0f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(-0x1.98ffe8p-1f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Log10 final {
				Log10() = delete;
				~Log10() = delete;
				Log10(const Log10&) = delete;
				Log10(Log10&&) = delete;
				Log10& operator=(const Log10&) = delete;
				Log10& operator=(Log10&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(-0x1.0p-110f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.dc215cp-2f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(-0x1.ec7c12p-3f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Sin final {
				Sin() = delete;
				~Sin() = delete;
				Sin(const Sin&) = delete;
				Sin(Sin&&) = delete;
				Sin& operator=(const Sin&) = delete;
				Sin& operator=(Sin&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.1p-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.55554p-3f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.11062ep-7f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(-0x1.9906cap-13f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Cos final {
				Cos() = delete;
				~Cos() = delete;
				Cos(const Cos&) = delete;
				Cos(Cos&&) = delete;
				Cos& operator=(const Cos&) = delete;
				Cos& operator=(Cos&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.1p-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.ffffap-2f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.553ce6p-5f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(-0x1.6424ap-10f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Tan final {
				Tan() = delete;
				~Tan() = delete;
				Tan(const Tan&) = delete;
				Tan(Tan&&) = delete;
				Tan& operator=(const Tan&) = delete;
				Tan& operator=(Tan&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.fffa5ap-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.579a9p-2f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.db9ee4p-4f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.80ebbap-4f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Asin final {
				Asin() = delete;
				~Asin() = delete;
				Asin(const Asin&) = delete;
				Asin(Asin&&) = delete;
				Asin& operator=(const Asin&) = delete;
				Asin& operator=(Asin&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.0001e4p+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.5120dp-3f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.87ef0cp-4f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Atan final {
				Atan() = delete;
				~Atan() = delete;
				Atan(const Atan&) = delete;
				Atan(Atan&&) = delete;
				Atan& operator=(const Atan&) = delete;
				Atan& operator=(Atan&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.ffdf9ap-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.4d0938p-2f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.3b964p-3f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(-0x1.633322p-5f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Sinh final {
				Sinh() = delete;
				~Sinh() = delete;
				Sinh(const Sinh&) = delete;
				Sinh(Sinh&&) = delete;
				Sinh& operator=(const Sinh&) = delete;
				Sinh& operator=(Sinh&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.0p+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.55547cp-3f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.123d82p-7f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Cosh final {
				Cosh() = delete;
				~Cosh() = delete;
				Cosh(const Cosh&) = delete;
				Cosh(Cosh&&) = delete;
				Cosh& operator=(const Cosh&) = delete;
				Cosh& operator=(Cosh&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.000002p+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.fffd0ap-2f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.576362p-5f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Asinh final {
				Asinh() = delete;
				~Asinh() = delete;
				Asinh(const Asinh&) = delete;
				Asinh(Asinh&&) = delete;
				Asinh& operator=(const Asinh&) = delete;
				Asinh& operator=(Asinh&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.fff2ccp-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.4d786ap-3f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.a622bcp-5f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Acosh final {
				Acosh() = delete;
				~Acosh() = delete;
				Acosh(const Acosh&) = delete;
				Acosh(Acosh&&) = delete;
				Acosh& operator=(const Acosh&) = delete;
				Acosh& operator=(Acosh&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.6a084ep+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.df194cp-4f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.611af2p-6f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Atanh final {
				Atanh() = delete;
				~Atanh() = delete;
				Atanh(const Atanh&) = delete;
				Atanh(Atanh&&) = delete;
				Atanh& operator=(const Atanh&) = delete;
				Atanh& operator=(Atanh&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.00064cp+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.4e542ep-2f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.12cebcp-2f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Erf final {
				Erf() = delete;
				~Erf() = delete;
				Erf(const Erf&) = delete;
				Erf(Erf&&) = delete;
				Erf& operator=(const Erf&) = delete;
				Erf& operator=(Erf&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.20db82p+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.802cbcp-2f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.ba0bcep-4f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(-0x1.2dded4p-6f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API ErfcAsymptotic final {
				ErfcAsymptotic() = delete;
				~ErfcAsymptotic() = delete;
				ErfcAsymptotic(const ErfcAsymptotic&) = delete;
				ErfcAsymptotic(ErfcAsymptotic&&) = delete;
				ErfcAsymptotic& operator=(const ErfcAsymptotic&) = delete;
				ErfcAsymptotic& operator=(ErfcAsymptotic&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.0p+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.0p-1f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.8p-1f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API SqrtSeed final {
				SqrtSeed() = delete;
				~SqrtSeed() = delete;
				SqrtSeed(const SqrtSeed&) = delete;
				SqrtSeed(SqrtSeed&&) = delete;
				SqrtSeed& operator=(const SqrtSeed&) = delete;
				SqrtSeed& operator=(SqrtSeed&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.669044p-3f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.433fa4p+0f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(-0x1.ac8a38p-1f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.df42c2p-2f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API RsqrtSeed final {
				RsqrtSeed() = delete;
				~RsqrtSeed() = delete;
				RsqrtSeed(const RsqrtSeed&) = delete;
				RsqrtSeed(RsqrtSeed&&) = delete;
				RsqrtSeed& operator=(const RsqrtSeed&) = delete;
				RsqrtSeed& operator=(RsqrtSeed&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.c6b9cep+0f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(-0x1.67cdcep+0f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(0x1.f3625ap-1f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(-0x1.7d02f2p-2f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API CbrtSeed final {
				CbrtSeed() = delete;
				~CbrtSeed() = delete;
				CbrtSeed(const CbrtSeed&) = delete;
				CbrtSeed(CbrtSeed&&) = delete;
				CbrtSeed& operator=(const CbrtSeed&) = delete;
				CbrtSeed& operator=(CbrtSeed&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.395abp-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.ba4fd4p-1f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(-0x1.23bd2cp-1f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.18e382p-2f); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Lanczos final {
				Lanczos() = delete;
				~Lanczos() = delete;
				Lanczos(const Lanczos&) = delete;
				Lanczos(Lanczos&&) = delete;
				Lanczos& operator=(const Lanczos&) = delete;
				Lanczos& operator=(Lanczos&&) = delete;

				static inline const __m256& c0() { static const __m256 v = _mm256_set1_ps(0x1.1p-1f); return v; }
				static inline const __m256& c1() { static const __m256 v = _mm256_set1_ps(0x1.52429cp+9f); return v; }
				static inline const __m256& c2() { static const __m256 v = _mm256_set1_ps(-0x1.3ac8e8p+10f); return v; }
				static inline const __m256& c3() { static const __m256 v = _mm256_set1_ps(0x1.81a966p+9f); return v; }
				static inline const __m256& c4() { static const __m256 v = _mm256_set1_ps(-0x1.613ae6p+7f); return v; }
				static inline const __m256& c5() { static const __m256 v = _mm256_set1_ps(0x1.903c28p+3f); return v; }
				static inline const __m256& c6() { static const __m256 v = _mm256_set1_ps(-0x1.1bcb2ap-3f); return v; }
				static inline const __m256& c7() { static const __m256 v = _mm256_set1_ps(0x1.4b045ap-17f); return v; }
			};
		} // namespace Approximate
	} // namespace FP32

	namespace FP64 {
		namespace Balanced {
			struct LEIBNIZ_RUNTIME_API Exp final {
				Exp() = delete;
				~Exp() = delete;
				Exp(const Exp&) = delete;
				Exp(Exp&&) = delete;
				Exp& operator=(const Exp&) = delete;
				Exp& operator=(Exp&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.0p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.000000a1fd6a7p+0); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.00000028794dfp-1); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.5554043e289bcp-3); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.5554ace120b86p-5); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.126fa6fd6e815p-7); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.6d7531eae5468p-10); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Expm1 final {
				Expm1() = delete;
				~Expm1() = delete;
				Expm1(const Expm1&) = delete;
				Expm1(Expm1&&) = delete;
				Expm1& operator=(const Expm1&) = delete;
				Expm1& operator=(Expm1&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.0p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.00000028794dfp-1); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.5555556750672p-3); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.5554ace120b86p-5); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.1110c63a4eedp-7); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.6d7531eae5468p-10); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.a15169e096556p-13); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Exp2 final {
				Exp2() = delete;
				~Exp2() = delete;
				Exp2(const Exp2&) = delete;
				Exp2(Exp2&&) = delete;
				Exp2& operator=(const Exp2&) = delete;
				Exp2& operator=(Exp2&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.0p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.62e4300881c7cp-1); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.ebfbe000ca124p-3); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.c6b025ee4a366p-5); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.3b2a931e876e3p-7); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.5e5f5e0421cbp-10); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.439e545c3ea41p-13); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Exp10 final {
				Exp10() = delete;
				~Exp10() = delete;
				Exp10(const Exp10&) = delete;
				Exp10(Exp10&&) = delete;
				Exp10& operator=(const Exp10&) = delete;
				Exp10& operator=(Exp10&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.0p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.26bb89ad792a1p+1); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.53526bffeca71p+1); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.0453c65b5f11ep+1); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.2bc6f9fb54aa7p+0); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.1b92cf22ad3dcp-1); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.b070655a64ecep-3); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Log1p final {
				Log1p() = delete;
				~Log1p() = delete;
				Log1p(const Log1p&) = delete;
				Log1p(Log1p&&) = delete;
				Log1p& operator=(const Log1p&) = delete;
				Log1p& operator=(Log1p&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.8d7991535d116p-18); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.ffff4d94c6107p-1); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(-0x1.0062bc78e07f5p-1); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.560698110ba1bp-2); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(-0x1.e23434a7ebd19p-3); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.7edf5b3ff3342p-3); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(-0x1.01ea76bbc4ecap-2); return v; }
				static inline const __m256d& c7() { static const __m256d v = _mm256_set1_pd(0x1.c0cfad98c53b4p-3); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Log2 final {
				Log2() = delete;
				~Log2() = delete;
				Log2(const Log2&) = delete;
				Log2(Log2&&) = delete;
				Log2& operator=(const Log2&) = delete;
				Log2& operator=(Log2&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.1eb7af09a833ap-17); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.7153f59f021bbp+0); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(-0x1.71e2e8906e383p-1); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.ed70597005a53p-2); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(-0x1.5bd62bf398f84p-2); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.142f2263e4ce6p-2); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(-0x1.74180d4905dbp-2); return v; }
				static inline const __m256d& c7() { static const __m256d v = _mm256_set1_pd(0x1.43bfb66774ef3p-2); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Log10 final {
				Log10() = delete;
				~Log10() = delete;
				Log10(const Log10&) = delete;
				Log10(Log10&&) = delete;
				Log10& operator=(const Log10&) = delete;
				Log10& operator=(Log10&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.593e06a240da5p-19); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.bcb716596ef52p-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(-0x1.bd63370d3230bp-3); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.29146dae7a7fap-3); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(-0x1.a2d646531efa7p-4); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.4c8f0e906d925p-4); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(-0x1.c00bb72eb21a3p-4); return v; }
				static inline const __m256d& c7() { static const __m256d v = _mm256_set1_pd(0x1.85d51e35149d8p-4); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Sin final {
				Sin() = delete;
				~Sin() = delete;
				Sin(const Sin&) = delete;
				Sin(Sin&&) = delete;
				Sin& operator=(const Sin&) = delete;
				Sin& operator=(Sin&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.1p-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.5555555555555p-3); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.1111111111111p-7); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.a01a01a01a014p-13); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.71de3a556bb7ep-19); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(-0x1.ae64567d9d7a9p-26); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.61245edeb306ap-33); return v; }
				static inline const __m256d& c7() { static const __m256d v = _mm256_set1_pd(-0x1.ae7b75b7f3ea8p-41); return v; }
				static inline const __m256d& c8() { static const __m256d v = _mm256_set1_pd(0x1.91e5d3ff5106bp-49); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Cos final {
				Cos() = delete;
				~Cos() = delete;
				Cos(const Cos&) = delete;
				Cos(Cos&&) = delete;
				Cos& operator=(const Cos&) = delete;
				Cos& operator=(Cos&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.1p-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.1p-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.5555555555555p-5); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.6c16c16c16c09p-10); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.a01a01a01844fp-16); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(-0x1.27e4fb7581302p-22); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.1eed8c32f1021p-29); return v; }
				static inline const __m256d& c7() { static const __m256d v = _mm256_set1_pd(-0x1.9392cccc6be36p-37); return v; }
				static inline const __m256d& c8() { static const __m256d v = _mm256_set1_pd(0x1.aa9bc439ae3a9p-45); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Tan final {
				Tan() = delete;
				~Tan() = delete;
				Tan(const Tan&) = delete;
				Tan(Tan&&) = delete;
				Tan& operator=(const Tan&) = delete;
				Tan& operator=(Tan&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.000000005a5b8p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.555553e31f706p-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.11118d1f228a7p-3); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.b9fbd9de55dfcp-5); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.68548d37e29e3p-6); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.10332abe2f058p-7); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.49f42392f1bf8p-8); return v; }
				static inline const __m256d& c7() { static const __m256d v = _mm256_set1_pd(-0x1.4c5d8d7f2d263p-11); return v; }
				static inline const __m256d& c8() { static const __m256d v = _mm256_set1_pd(0x1.0d67c14888fd1p-9); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Asin final {
				Asin() = delete;
				~Asin() = delete;
				Asin(const Asin&) = delete;
				Asin(Asin&&) = delete;
				Asin& operator=(const Asin&) = delete;
				Asin& operator=(Asin&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.ffffffffe1fddp-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.55555644ffd27p-3); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.3332974333413p-4); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.6ddd3297735ebp-5); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.ed3310aa58a51p-6); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.93e1363c82c76p-6); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.e5084c0c9e239p-8); return v; }
				static inline const __m256d& c7() { static const __m256d v = _mm256_set1_pd(0x1.1ca8ba846c6cbp-5); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Atan final {
				Atan() = delete;
				~Atan() = delete;
				Atan(const Atan&) = delete;
				Atan(Atan&&) = delete;
				Atan& operator=(const Atan&) = delete;
				Atan& operator=(Atan&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.ffffffe79bf93p-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.55552f0db432p-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.998f82493d066p-3); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.240b8d994abf9p-3); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.bfc9e8c2b0243p-4); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(-0x1.5601364b1cac3p-4); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.d3ad79f53e142p-5); return v; }
				static inline const __m256d& c7() { static const __m256d v = _mm256_set1_pd(-0x1.f148f2a829af1p-6); return v; }
				static inline const __m256d& c8() { static const __m256d v = _mm256_set1_pd(0x1.57a8c747ed314p-7); return v; }
				static inline const __m256d& c9() { static const __m256d v = _mm256_set1_pd(-0x1.bdf39729124b6p-10); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Sinh final {
				Sinh() = delete;
				~Sinh() = delete;
				Sinh(const Sinh&) = delete;
				Sinh(Sinh&&) = delete;
				Sinh& operator=(const Sinh&) = delete;
				Sinh& operator=(Sinh&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.0p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.5555555555555p-3); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.1111111111113p-7); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.a01a01a0185b8p-13); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.71de3a5f3a85fp-19); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.ae641aa4b3bc4p-26); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.61d987751d063p-33); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Cosh final {
				Cosh() = delete;
				~Cosh() = delete;
				Cosh(const Cosh&) = delete;
				Cosh(Cosh&&) = delete;
				Cosh& operator=(const Cosh&) = delete;
				Cosh& operator=(Cosh&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.0p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.1p-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.555555555555dp-5); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.6c16c16c13a9dp-10); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.a01a01b27d442p-16); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.27e4c358312d7p-22); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.1f97684759d2cp-29); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Asinh final {
				Asinh() = delete;
				~Asinh() = delete;
				Asinh(const Asinh&) = delete;
				Asinh(Asinh&&) = delete;
				Asinh& operator=(const Asinh&) = delete;
				Asinh& operator=(Asinh&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.ffffffffd31a3p-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.5555546833a3bp-3); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.3332cb1306bap-4); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.6da50cdef9bd8p-5); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.f03a9698a9a1ap-6); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(-0x1.64a1d4e884e18p-6); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.eb17f1de08ap-7); return v; }
				static inline const __m256d& c7() { static const __m256d v = _mm256_set1_pd(-0x1.0afc2605b475ap-7); return v; }
				static inline const __m256d& c8() { static const __m256d v = _mm256_set1_pd(0x1.38db71d294bacp-9); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Acosh final {
				Acosh() = delete;
				~Acosh() = delete;
				Acosh(const Acosh&) = delete;
				Acosh(Acosh&&) = delete;
				Acosh& operator=(const Acosh&) = delete;
				Acosh& operator=(Acosh&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.6a09e667efe68p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.e2b7dda271da1p-4); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.b2721effa4bf4p-6); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.0294304858003p-7); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.5f548154f92bfp-9); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(-0x1.fabbd22ca2814p-11); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.5677d4f887a75p-12); return v; }
				static inline const __m256d& c7() { static const __m256d v = _mm256_set1_pd(-0x1.2dd8e606c72cbp-14); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Atanh final {
				Atanh() = delete;
				~Atanh() = delete;
				Atanh(const Atanh&) = delete;
				Atanh(Atanh&&) = delete;
				Atanh& operator=(const Atanh&) = delete;
				Atanh& operator=(Atanh&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.ffffffff5e368p-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.555557db56886p-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.9997f57975c75p-3); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.24c5e33e88f82p-3); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.c0f55975c35e6p-4); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.a66a48ce8cef7p-4); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.859eb5c8eb941p-6); return v; }
				static inline const __m256d& c7() { static const __m256d v = _mm256_set1_pd(0x1.69d411adf045dp-3); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Erf final {
				Erf() = delete;
				~Erf() = delete;
				Erf(const Erf&) = delete;
				Erf(Erf&&) = delete;
				Erf& operator=(const Erf&) = delete;
				Erf& operator=(Erf&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.20dd750429b19p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.812746b0271ecp-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.ce2f2197bc2efp-4); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.b82ce15c3b7f8p-6); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.565ba0406c001p-8); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(-0x1.c0286cad68e02p-11); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(0x1.f941bed7e7847p-14); return v; }
				static inline const __m256d& c7() { static const __m256d v = _mm256_set1_pd(-0x1.f0705a1dde9aap-17); return v; }
				static inline const __m256d& c8() { static const __m256d v = _mm256_set1_pd(0x1.9ae0986f9de4fp-20); return v; }
				static inline const __m256d& c9() { static const __m256d v = _mm256_set1_pd(-0x1.c1a515de8637ap-24); return v; }
			};

			struct LEIBNIZ_RUNTIME_API ErfcAsymptotic final {
				ErfcAsymptotic() = delete;
				~ErfcAsymptotic() = delete;
				ErfcAsymptotic(const ErfcAsymptotic&) = delete;
				ErfcAsymptotic(ErfcAsymptotic&&) = delete;
				ErfcAsymptotic& operator=(const ErfcAsymptotic&) = delete;
				ErfcAsymptotic& operator=(ErfcAsymptotic&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.0p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.0p-1); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.8p-1); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.ep+0); return v; }
			};

			struct LEIBNIZ_RUNTIME_API SqrtSeed final {
				SqrtSeed() = delete;
				~SqrtSeed() = delete;
				SqrtSeed(const SqrtSeed&) = delete;
				SqrtSeed(SqrtSeed&&) = delete;
				SqrtSeed& operator=(const SqrtSeed&) = delete;
				SqrtSeed& operator=(SqrtSeed&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.669044b27e55fp-3); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.433fa4f9223f1p+0); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(-0x1.ac8a37f93cd48p-1); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.df42c1629a518p-2); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(-0x1.42c35908092b3p-4); return v; }
			};

			struct LEIBNIZ_RUNTIME_API RsqrtSeed final {
				RsqrtSeed() = delete;
				~RsqrtSeed() = delete;
				RsqrtSeed(const RsqrtSeed&) = delete;
				RsqrtSeed(RsqrtSeed&&) = delete;
				RsqrtSeed& operator=(const RsqrtSeed&) = delete;
				RsqrtSeed& operator=(RsqrtSeed&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.c6b9cdfab5492p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.67cdcdd30e8ddp+0); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.f3625a4e67596p-1); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.7d02f10610a8p-2); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.cd28767f57645p-5); return v; }
			};

			struct LEIBNIZ_RUNTIME_API CbrtSeed final {
				CbrtSeed() = delete;
				~CbrtSeed() = delete;
				CbrtSeed(const CbrtSeed&) = delete;
				CbrtSeed(CbrtSeed&&) = delete;
				CbrtSeed& operator=(const CbrtSeed&) = delete;
				CbrtSeed& operator=(CbrtSeed&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.395aafeedb4p-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.ba4fd4ac561dfp-1); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(-0x1.23bd2bd853685p-1); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.18e3815d16328p-2); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(-0x1.e2ee2147bdd1fp-5); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Lanczos final {
				Lanczos() = delete;
				~Lanczos() = delete;
				Lanczos(const Lanczos&) = delete;
				Lanczos(Lanczos&&) = delete;
				Lanczos& operator=(const Lanczos&) = delete;
				Lanczos& operator=(Lanczos&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.ffffffffff95p-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.52429b6c30b05p+9); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(-0x1.3ac8e8ed4171bp+10); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.81a9661d3b4d8p+9); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(-0x1.613ae51a32f5dp+7); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.903c27f8b9c81p+3); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(-0x1.1bcb2992b2855p-3); return v; }
				static inline const __m256d& c7() { static const __m256d v = _mm256_set1_pd(0x1.4b045a9e6c012p-17); return v; }
				static inline const __m256d& c8() { static const __m256d v = _mm256_set1_pd(0x1.433a1cc831b75p-23); return v; }
			};
		} // namespace Balanced

		namespace Approximate {
			struct LEIBNIZ_RUNTIME_API Exp final {
				Exp() = delete;
				~Exp() = delete;
				Exp(const Exp&) = delete;
				Exp(Exp&&) = delete;
				Exp& operator=(const Exp&) = delete;
				Exp& operator=(Exp&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.0p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.fffb0ed184294p-1); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.fffe5aa63cb93p-2); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.57e730d6db7bbp-3); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.570b976d7eabfp-5); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Expm1 final {
				Expm1() = delete;
				~Expm1() = delete;
				Expm1(const Expm1&) = delete;
				Expm1(Expm1&&) = delete;
				Expm1& operator=(const Expm1&) = delete;
				Expm1& operator=(Expm1&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.0p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.fffe5aa63cb93p-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.5554dd04e58bep-3); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.570b976d7eabfp-5); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.120b616c43f75p-7); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Exp2 final {
				Exp2() = delete;
				~Exp2() = delete;
				Exp2(const Exp2&) = delete;
				Exp2(Exp2&&) = delete;
				Exp2& operator=(const Exp2&) = delete;
				Exp2& operator=(Exp2&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.0p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.62e365e1121f6p-1); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.ebfb82a3aea0bp-3); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.c854f68eba124p-5); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.3beceb44761e5p-7); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Exp10 final {
				Exp10() = delete;
				~Exp10() = delete;
				Exp10(const Exp10&) = delete;
				Exp10(Exp10&&) = delete;
				Exp10& operator=(const Exp10&) = delete;
				Exp10& operator=(Exp10&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.0p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.2669e62ee05c6p+1); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.533347ca7eb8bp+1); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.0ef698e2ecd8dp+1); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.33e3775c26ab2p+0); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Log1p final {
				Log1p() = delete;
				~Log1p() = delete;
				Log1p(const Log1p&) = delete;
				Log1p(Log1p&&) = delete;
				Log1p& operator=(const Log1p&) = delete;
				Log1p& operator=(Log1p&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(-0x1.0p-138); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.fd72336722531p-1); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(-0x1.fbb0efea42193p-2); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.a354556c0709ep-2); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(-0x1.41a74ab561c2cp-2); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Log2 final {
				Log2() = delete;
				~Log2() = delete;
				Log2(const Log2&) = delete;
				Log2(Log2&&) = delete;
				Log2& operator=(const Log2&) = delete;
				Log2& operator=(Log2&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(-0x1.6dp-138); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.6f7cd883e3903p+0); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(-0x1.6e38c5437e568p-1); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.2e7b744e8dd6ep-1); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(-0x1.d00c423f00dfcp-2); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Log10 final {
				Log10() = delete;
				~Log10() = delete;
				Log10(const Log10&) = delete;
				Log10(Log10&&) = delete;
				Log10& operator=(const Log10&) = delete;
				Log10& operator=(Log10&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(-0x1.34p-140); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.ba7fcf54cef43p-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(-0x1.b8f9959f4d36ap-3); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.6c3993f2609ap-3); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(-0x1.1762797a9d07cp-3); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Sin final {
				Sin() = delete;
				~Sin() = delete;
				Sin(const Sin&) = delete;
				Sin(Sin&&) = delete;
				Sin& operator=(const Sin&) = delete;
				Sin& operator=(Sin&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.fffffffffffd9p-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.5555555550efep-3); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.1111110bde5e3p-7); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.a019f8a207d3fp-13); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.71d7317b8ee33p-19); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(-0x1.a9507f3711e2dp-26); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Cos final {
				Cos() = delete;
				~Cos() = delete;
				Cos(const Cos&) = delete;
				Cos(Cos&&) = delete;
				Cos& operator=(const Cos&) = delete;
				Cos& operator=(Cos&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.ffffffffffe0bp-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.ffffffffe3763p-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.5555554476425p-5); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.6c16b2d3e61f5p-10); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.a00e9685da9c4p-16); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(-0x1.23c5c15441ap-22); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Tan final {
				Tan() = delete;
				~Tan() = delete;
				Tan(const Tan&) = delete;
				Tan(Tan&&) = delete;
				Tan& operator=(const Tan&) = delete;
				Tan& operator=(Tan&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.fffff88c9c162p-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.555c1aa017c8fp-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.10158d12320c6p-3); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.d44a862e47de4p-5); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.9bb3cce75e6a5p-7); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.4db42acf4e25ep-6); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Asin final {
				Asin() = delete;
				~Asin() = delete;
				Asin(const Asin&) = delete;
				Asin(Asin&&) = delete;
				Asin& operator=(const Asin&) = delete;
				Asin& operator=(Asin&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.00000137fe155p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.554dbf185abeep-3); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.350eaed06a2d5p-4); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.45feff0af4e96p-5); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.9c87b69ffd0f5p-5); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Atan final {
				Atan() = delete;
				~Atan() = delete;
				Atan(const Atan&) = delete;
				Atan(Atan&&) = delete;
				Atan& operator=(const Atan&) = delete;
				Atan& operator=(Atan&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.ffff52add7cbdp-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.54f2b56f390a5p-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.9011df7c714e8p-3); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.ed5b7ee5714bep-4); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.cf95ccf6dc4c9p-5); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(-0x1.ae41a0cc72a89p-7); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Sinh final {
				Sinh() = delete;
				~Sinh() = delete;
				Sinh(const Sinh&) = delete;
				Sinh(Sinh&&) = delete;
				Sinh& operator=(const Sinh&) = delete;
				Sinh& operator=(Sinh&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.0000000000006p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.5555555550d88p-3); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.11111123bf154p-7); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.a01994c849582p-13); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.72e107c874de9p-19); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Cosh final {
				Cosh() = delete;
				~Cosh() = delete;
				Cosh(const Cosh&) = delete;
				Cosh(Cosh&&) = delete;
				Cosh& operator=(const Cosh&) = delete;
				Cosh& operator=(Cosh&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.000000000003dp+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.ffffffffe74f1p-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.55555588b8403p-5); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.6c162bb7d965cp-10); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.a17df0d914d6cp-16); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Asinh final {
				Asinh() = delete;
				~Asinh() = delete;
				Asinh(const Asinh&) = delete;
				Asinh(Asinh&&) = delete;
				Asinh& operator=(const Asinh&) = delete;
				Asinh& operator=(Asinh&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.fffffeb87136cp-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.55525256d6e19p-3); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.329cfb7132e28p-4); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.62b33c784e945p-5); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.8f72d64b4487p-6); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(-0x1.165b11aa660f5p-7); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Acosh final {
				Acosh() = delete;
				~Acosh() = delete;
				Acosh(const Acosh&) = delete;
				Acosh(Acosh&&) = delete;
				Acosh& operator=(const Acosh&) = delete;
				Acosh& operator=(Acosh&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.6a09e5c26a954p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.e2b3cf54b0e0dp-4); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.b16970f172561p-6); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.ecfc95a0a290dp-8); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.cc0297ccbef79p-10); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Atanh final {
				Atanh() = delete;
				~Atanh() = delete;
				Atanh(const Atanh&) = delete;
				Atanh(Atanh&&) = delete;
				Atanh& operator=(const Atanh&) = delete;
				Atanh& operator=(Atanh&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.000005356fbd4p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.5545203965275p-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.9d8f88475479ap-3); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.f4c8aeef23538p-4); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.8fc48a7c4bd6dp-3); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Erf final {
				Erf() = delete;
				~Erf() = delete;
				Erf(const Erf&) = delete;
				Erf(Erf&&) = delete;
				Erf& operator=(const Erf&) = delete;
				Erf& operator=(Erf&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.20dd74546d3e7p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.812680a1a33f4p-2); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.ce0ab171c3ee9p-4); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.b5b30f0f42c6cp-6); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(0x1.428d76f2cc227p-8); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(-0x1.281ef9ed3249cp-11); return v; }
			};

			struct LEIBNIZ_RUNTIME_API ErfcAsymptotic final {
				ErfcAsymptotic() = delete;
				~ErfcAsymptotic() = delete;
				ErfcAsymptotic(const ErfcAsymptotic&) = delete;
				ErfcAsymptotic(ErfcAsymptotic&&) = delete;
				ErfcAsymptotic& operator=(const ErfcAsymptotic&) = delete;
				ErfcAsymptotic& operator=(ErfcAsymptotic&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.0p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.0p-1); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.8p-1); return v; }
			};

			struct LEIBNIZ_RUNTIME_API SqrtSeed final {
				SqrtSeed() = delete;
				~SqrtSeed() = delete;
				SqrtSeed(const SqrtSeed&) = delete;
				SqrtSeed(SqrtSeed&&) = delete;
				SqrtSeed& operator=(const SqrtSeed&) = delete;
				SqrtSeed& operator=(SqrtSeed&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.669044b27e55fp-3); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.433fa4f9223f1p+0); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(-0x1.ac8a37f93cd48p-1); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.df42c1629a518p-2); return v; }
			};

			struct LEIBNIZ_RUNTIME_API RsqrtSeed final {
				RsqrtSeed() = delete;
				~RsqrtSeed() = delete;
				RsqrtSeed(const RsqrtSeed&) = delete;
				RsqrtSeed(RsqrtSeed&&) = delete;
				RsqrtSeed& operator=(const RsqrtSeed&) = delete;
				RsqrtSeed& operator=(RsqrtSeed&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.c6b9cdfab5492p+0); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(-0x1.67cdcdd30e8ddp+0); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(0x1.f3625a4e67596p-1); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(-0x1.7d02f10610a8p-2); return v; }
			};

			struct LEIBNIZ_RUNTIME_API CbrtSeed final {
				CbrtSeed() = delete;
				~CbrtSeed() = delete;
				CbrtSeed(const CbrtSeed&) = delete;
				CbrtSeed(CbrtSeed&&) = delete;
				CbrtSeed& operator=(const CbrtSeed&) = delete;
				CbrtSeed& operator=(CbrtSeed&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.395aafeedb4p-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.ba4fd4ac561dfp-1); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(-0x1.23bd2bd853685p-1); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.18e3815d16328p-2); return v; }
			};

			struct LEIBNIZ_RUNTIME_API Lanczos final {
				Lanczos() = delete;
				~Lanczos() = delete;
				Lanczos(const Lanczos&) = delete;
				Lanczos(Lanczos&&) = delete;
				Lanczos& operator=(const Lanczos&) = delete;
				Lanczos& operator=(Lanczos&&) = delete;

				static inline const __m256d& c0() { static const __m256d v = _mm256_set1_pd(0x1.ffffffffff95p-1); return v; }
				static inline const __m256d& c1() { static const __m256d v = _mm256_set1_pd(0x1.52429b6c30b05p+9); return v; }
				static inline const __m256d& c2() { static const __m256d v = _mm256_set1_pd(-0x1.3ac8e8ed4171bp+10); return v; }
				static inline const __m256d& c3() { static const __m256d v = _mm256_set1_pd(0x1.81a9661d3b4d8p+9); return v; }
				static inline const __m256d& c4() { static const __m256d v = _mm256_set1_pd(-0x1.613ae51a32f5dp+7); return v; }
				static inline const __m256d& c5() { static const __m256d v = _mm256_set1_pd(0x1.903c27f8b9c81p+3); return v; }
				static inline const __m256d& c6() { static const __m256d v = _mm256_set1_pd(-0x1.1bcb2992b2855p-3); return v; }
				static inline const __m256d& c7() { static const __m256d v = _mm256_set1_pd(0x1.4b045a9e6c012p-17); return v; }
			};
		}
	}
}