// ElementwiseScalarKernels.h
// AUTO-GENERATED by gen_scalar_kernels.py - DO NOT EDIT BY HAND
//
// Scalar unrolled transcendental kernels for Balanced and Approximate tiers.
// Used exclusively as tail handlers by ElementwiseVectorKernels.h.
// N is a compile-time constant - compiler fully unrolls staticFor.
//
// Naming: unrolledScalar{Op}{Tier}_{type}<N>
//   Op:   Exp, Expm1, Exp2, Exp10, Log1p, Log2, Log10,
//         Sin, Cos, Tan, Asin, Atan,
//         Sinh, Cosh, Asinh, Acosh, Atanh,
//         Erf, ErfcAsymptotic, SqrtSeed, RsqrtSeed, CbrtSeed, Lanczos
//   Tier: Balanced | Approximate
//   type: f32 | f64
//
// Usage:
//   unrolledScalarExpBalanced_f32<3>(in + offset, out + offset);
//   unrolledScalarExpApproximate_f64<5>(in + offset, out + offset);
//
// Section map:
//   Exp family ...................................... ~line 60
//   Log family ...................................... ~line 260
//   Trig family ..................................... ~line 460
//   Hyp family ...................................... ~line 700
//   Special family .................................. ~line 900
//   Root family ..................................... ~line 1060

#pragma once
#include <bit>
#include "StaticPipelines.h"
#include "LeibnizCompiler.h"
#include "LeibnizFloat.h"
#include "LeibnizDiagnostics.h"

namespace Leibniz::LinAlg::Internal::Kernels::Scalar {
	// Exp - base-e exponential, Horner(x, c)
	// Balanced:    4 terms (f32)   7 terms (f64)
	// Approximate: 3 terms (f32)   5 terms (f64)

	// --- Exp Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExpBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.fff61cp-1f + in[i] * (0x1.fffe06p-1f + in[i] * (0x1.029248p-1f + in[i] * 0x1.57636ep-3f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.fff61cp-1f + in[idx] * (0x1.fffe06p-1f + in[idx] * (0x1.029248p-1f + in[idx] * 0x1.57636ep-3f)));
										 });
#endif
	}

	// --- Exp Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExpApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0f + in[i] * (0x1.03dc68p+0f + in[i] * 0x1.01ed76p-1f));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0f + in[idx] * (0x1.03dc68p+0f + in[idx] * 0x1.01ed76p-1f));
										 });
#endif
	}

	// --- Exp Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExpBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0 + in[i] * (0x1.000000a1fd6a7p+0 + in[i] * (0x1.00000028794dfp-1 + in[i] * (0x1.5554043e289bcp-3 + in[i] * (0x1.5554ace120b86p-5 + in[i] * (0x1.126fa6fd6e815p-7 + in[i] * 0x1.6d7531eae5468p-10))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0 + in[idx] * (0x1.000000a1fd6a7p+0 + in[idx] * (0x1.00000028794dfp-1 + in[idx] * (0x1.5554043e289bcp-3 + in[idx] * (0x1.5554ace120b86p-5 + in[idx] * (0x1.126fa6fd6e815p-7 + in[idx] * 0x1.6d7531eae5468p-10))))));
										 });
#endif
	}

	// --- Exp Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExpApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0 + in[i] * (0x1.fffb0ed184294p-1 + in[i] * (0x1.fffe5aa63cb93p-2 + in[i] * (0x1.57e730d6db7bbp-3 + in[i] * 0x1.570b976d7eabfp-5))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0 + in[idx] * (0x1.fffb0ed184294p-1 + in[idx] * (0x1.fffe5aa63cb93p-2 + in[idx] * (0x1.57e730d6db7bbp-3 + in[idx] * 0x1.570b976d7eabfp-5))));
										 });
#endif
	}

	// Expm1 - exp(x)-1, x * Horner(x, c)
	// Balanced:    4 terms (f32)   7 terms (f64)
	// Approximate: 3 terms (f32)   5 terms (f64)

	// --- Expm1 Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExpm1Balanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.fffe06p-1f + in[i] * (0x1.ffff58p-2f + in[i] * (0x1.57636ep-3f + in[i] * 0x1.56b3d8p-5f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.fffe06p-1f + in[idx] * (0x1.ffff58p-2f + in[idx] * (0x1.57636ep-3f + in[idx] * 0x1.56b3d8p-5f)));
										 });
#endif
	}

	// --- Expm1 Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExpm1Approximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0f + in[i] * (0x1.01ed76p-1f + in[i] * 0x1.56dfc4p-3f));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0f + in[idx] * (0x1.01ed76p-1f + in[idx] * 0x1.56dfc4p-3f));
										 });
#endif
	}

	// --- Expm1 Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExpm1Balanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0 + in[i] * (0x1.00000028794dfp-1 + in[i] * (0x1.5555556750672p-3 + in[i] * (0x1.5554ace120b86p-5 + in[i] * (0x1.1110c63a4eedp-7 + in[i] * (0x1.6d7531eae5468p-10 + in[i] * 0x1.a15169e096556p-13))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0 + in[idx] * (0x1.00000028794dfp-1 + in[idx] * (0x1.5555556750672p-3 + in[idx] * (0x1.5554ace120b86p-5 + in[idx] * (0x1.1110c63a4eedp-7 + in[idx] * (0x1.6d7531eae5468p-10 + in[idx] * 0x1.a15169e096556p-13))))));
										 });
#endif
	}

	// --- Expm1 Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExpm1Approximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0 + in[i] * (0x1.fffe5aa63cb93p-2 + in[i] * (0x1.5554dd04e58bep-3 + in[i] * (0x1.570b976d7eabfp-5 + in[i] * 0x1.120b616c43f75p-7))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0 + in[idx] * (0x1.fffe5aa63cb93p-2 + in[idx] * (0x1.5554dd04e58bep-3 + in[idx] * (0x1.570b976d7eabfp-5 + in[idx] * 0x1.120b616c43f75p-7))));
										 });
#endif
	}

	// Exp2 - base-2 exponential, Horner(x, c)
	// Balanced:    4 terms (f32)   7 terms (f64)
	// Approximate: 3 terms (f32)   5 terms (f64)

	// --- Exp2 Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExp2Balanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.fffdb8p-1f + in[i] * (0x1.62e3ep-1f + in[i] * (0x1.ee5a96p-3f + in[i] * 0x1.c800d2p-5f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.fffdb8p-1f + in[idx] * (0x1.62e3ep-1f + in[idx] * (0x1.ee5a96p-3f + in[idx] * 0x1.c800d2p-5f)));
										 });
#endif
	}

	// --- Exp2 Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExp2Approximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0f + in[i] * (0x1.6574fap-1f + in[i] * 0x1.edc2ccp-3f));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0f + in[idx] * (0x1.6574fap-1f + in[idx] * 0x1.edc2ccp-3f));
										 });
#endif
	}

	// --- Exp2 Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExp2Balanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0 + in[i] * (0x1.62e4300881c7cp-1 + in[i] * (0x1.ebfbe000ca124p-3 + in[i] * (0x1.c6b025ee4a366p-5 + in[i] * (0x1.3b2a931e876e3p-7 + in[i] * (0x1.5e5f5e0421cbp-10 + in[i] * 0x1.439e545c3ea41p-13))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0 + in[idx] * (0x1.62e4300881c7cp-1 + in[idx] * (0x1.ebfbe000ca124p-3 + in[idx] * (0x1.c6b025ee4a366p-5 + in[idx] * (0x1.3b2a931e876e3p-7 + in[idx] * (0x1.5e5f5e0421cbp-10 + in[idx] * 0x1.439e545c3ea41p-13))))));
										 });
#endif
	}

	// --- Exp2 Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExp2Approximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0 + in[i] * (0x1.62e365e1121f6p-1 + in[i] * (0x1.ebfb82a3aea0bp-3 + in[i] * (0x1.c854f68eba124p-5 + in[i] * 0x1.3beceb44761e5p-7))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0 + in[idx] * (0x1.62e365e1121f6p-1 + in[idx] * (0x1.ebfb82a3aea0bp-3 + in[idx] * (0x1.c854f68eba124p-5 + in[idx] * 0x1.3beceb44761e5p-7))));
										 });
#endif
	}

	// Exp10 - base-10 exponential, Horner(x, c)
	// Balanced:    4 terms (f32)   7 terms (f64)
	// Approximate: 3 terms (f32)   5 terms (f64)

	// --- Exp10 Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExp10Balanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.fee536p-1f + in[i] * (0x1.269acp+1f + in[i] * (0x1.65aaacp+1f + in[i] * 0x1.0cd7acp+1f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.fee536p-1f + in[idx] * (0x1.269acp+1f + in[idx] * (0x1.65aaacp+1f + in[idx] * 0x1.0cd7acp+1f)));
										 });
#endif
	}

	// --- Exp10 Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExp10Approximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0f + in[i] * (0x1.3ec25cp+1f + in[i] * 0x1.610b4p+1f));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0f + in[idx] * (0x1.3ec25cp+1f + in[idx] * 0x1.610b4p+1f));
										 });
#endif
	}

	// --- Exp10 Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExp10Balanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0 + in[i] * (0x1.26bb89ad792a1p+1 + in[i] * (0x1.53526bffeca71p+1 + in[i] * (0x1.0453c65b5f11ep+1 + in[i] * (0x1.2bc6f9fb54aa7p+0 + in[i] * (0x1.1b92cf22ad3dcp-1 + in[i] * 0x1.b070655a64ecep-3))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0 + in[idx] * (0x1.26bb89ad792a1p+1 + in[idx] * (0x1.53526bffeca71p+1 + in[idx] * (0x1.0453c65b5f11ep+1 + in[idx] * (0x1.2bc6f9fb54aa7p+0 + in[idx] * (0x1.1b92cf22ad3dcp-1 + in[idx] * 0x1.b070655a64ecep-3))))));
										 });
#endif
	}

	// --- Exp10 Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarExp10Approximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0 + in[i] * (0x1.2669e62ee05c6p+1 + in[i] * (0x1.533347ca7eb8bp+1 + in[i] * (0x1.0ef698e2ecd8dp+1 + in[i] * 0x1.33e3775c26ab2p+0))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0 + in[idx] * (0x1.2669e62ee05c6p+1 + in[idx] * (0x1.533347ca7eb8bp+1 + in[idx] * (0x1.0ef698e2ecd8dp+1 + in[idx] * 0x1.33e3775c26ab2p+0))));
										 });
#endif
	}

	// Log1p - log(1+x), Horner(x, c)
	// Balanced:    5 terms (f32)   8 terms (f64)
	// Approximate: 3 terms (f32)   5 terms (f64)

	// --- Log1p Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLog1pBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (-0x1.5ap-109f + in[i] * (0x1.fd7234p-1f + in[i] * (-0x1.fbb0fp-2f + in[i] * (0x1.a35456p-2f + in[i] * -0x1.41a74ap-2f))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (-0x1.5ap-109f + in[idx] * (0x1.fd7234p-1f + in[idx] * (-0x1.fbb0fp-2f + in[idx] * (0x1.a35456p-2f + in[idx] * -0x1.41a74ap-2f))));
										 });
#endif
	}

	// --- Log1p Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLog1pApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (-0x1.0p-109f + in[i] * (0x1.121528p+0f + in[i] * -0x1.1b7f38p-1f));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (-0x1.0p-109f + in[idx] * (0x1.121528p+0f + in[idx] * -0x1.1b7f38p-1f));
										 });
#endif
	}

	// --- Log1p Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLog1pBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.8d7991535d116p-18 + in[i] * (0x1.ffff4d94c6107p-1 + in[i] * (-0x1.0062bc78e07f5p-1 + in[i] * (0x1.560698110ba1bp-2 + in[i] * (-0x1.e23434a7ebd19p-3 + in[i] * (0x1.7edf5b3ff3342p-3 + in[i] * (-0x1.01ea76bbc4ecap-2 + in[i] * 0x1.c0cfad98c53b4p-3)))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.8d7991535d116p-18 + in[idx] * (0x1.ffff4d94c6107p-1 + in[idx] * (-0x1.0062bc78e07f5p-1 + in[idx] * (0x1.560698110ba1bp-2 + in[idx] * (-0x1.e23434a7ebd19p-3 + in[idx] * (0x1.7edf5b3ff3342p-3 + in[idx] * (-0x1.01ea76bbc4ecap-2 + in[idx] * 0x1.c0cfad98c53b4p-3)))))));
										 });
#endif
	}

	// --- Log1p Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLog1pApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (-0x1.0p-138 + in[i] * (0x1.fd72336722531p-1 + in[i] * (-0x1.fbb0efea42193p-2 + in[i] * (0x1.a354556c0709ep-2 + in[i] * -0x1.41a74ab561c2cp-2))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (-0x1.0p-138 + in[idx] * (0x1.fd72336722531p-1 + in[idx] * (-0x1.fbb0efea42193p-2 + in[idx] * (0x1.a354556c0709ep-2 + in[idx] * -0x1.41a74ab561c2cp-2))));
										 });
#endif
	}

	// Log2 - base-2 logarithm, Horner(x, c)
	// Balanced:    5 terms (f32)   8 terms (f64)
	// Approximate: 3 terms (f32)   5 terms (f64)

	// --- Log2 Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLog2Balanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (-0x1.0p-108f + in[i] * (0x1.6f7cd8p+0f + in[i] * (-0x1.6e38c6p-1f + in[i] * (0x1.2e7b74p-1f + in[i] * -0x1.d00c42p-2f))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (-0x1.0p-108f + in[idx] * (0x1.6f7cd8p+0f + in[idx] * (-0x1.6e38c6p-1f + in[idx] * (0x1.2e7b74p-1f + in[idx] * -0x1.d00c42p-2f))));
										 });
#endif
	}

	// --- Log2 Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLog2Approximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (-0x1.4p-109f + in[i] * (0x1.8b6aecp+0f + in[i] * -0x1.98ffe8p-1f));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (-0x1.4p-109f + in[idx] * (0x1.8b6aecp+0f + in[idx] * -0x1.98ffe8p-1f));
										 });
#endif
	}

	// --- Log2 Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLog2Balanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.1eb7af09a833ap-17 + in[i] * (0x1.7153f59f021bbp+0 + in[i] * (-0x1.71e2e8906e383p-1 + in[i] * (0x1.ed70597005a53p-2 + in[i] * (-0x1.5bd62bf398f84p-2 + in[i] * (0x1.142f2263e4ce6p-2 + in[i] * (-0x1.74180d4905dbp-2 + in[i] * 0x1.43bfb66774ef3p-2)))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.1eb7af09a833ap-17 + in[idx] * (0x1.7153f59f021bbp+0 + in[idx] * (-0x1.71e2e8906e383p-1 + in[idx] * (0x1.ed70597005a53p-2 + in[idx] * (-0x1.5bd62bf398f84p-2 + in[idx] * (0x1.142f2263e4ce6p-2 + in[idx] * (-0x1.74180d4905dbp-2 + in[idx] * 0x1.43bfb66774ef3p-2)))))));
										 });
#endif
	}

	// --- Log2 Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLog2Approximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (-0x1.6dp-138 + in[i] * (0x1.6f7cd883e3903p+0 + in[i] * (-0x1.6e38c5437e568p-1 + in[i] * (0x1.2e7b744e8dd6ep-1 + in[i] * -0x1.d00c423f00dfcp-2))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (-0x1.6dp-138 + in[idx] * (0x1.6f7cd883e3903p+0 + in[idx] * (-0x1.6e38c5437e568p-1 + in[idx] * (0x1.2e7b744e8dd6ep-1 + in[idx] * -0x1.d00c423f00dfcp-2))));
										 });
#endif
	}

	// Log10 - base-10 logarithm, Horner(x, c)
	// Balanced:    5 terms (f32)   8 terms (f64)
	// Approximate: 3 terms (f32)   5 terms (f64)

	// --- Log10 Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLog10Balanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (-0x1.76p-110f + in[i] * (0x1.ba7fdp-2f + in[i] * (-0x1.b8f996p-3f + in[i] * (0x1.6c3994p-3f + in[i] * -0x1.17627ap-3f))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (-0x1.76p-110f + in[idx] * (0x1.ba7fdp-2f + in[idx] * (-0x1.b8f996p-3f + in[idx] * (0x1.6c3994p-3f + in[idx] * -0x1.17627ap-3f))));
										 });
#endif
	}

	// --- Log10 Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLog10Approximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (-0x1.0p-110f + in[i] * (0x1.dc215cp-2f + in[i] * -0x1.ec7c12p-3f));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (-0x1.0p-110f + in[idx] * (0x1.dc215cp-2f + in[idx] * -0x1.ec7c12p-3f));
										 });
#endif
	}

	// --- Log10 Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLog10Balanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.593e06a240da5p-19 + in[i] * (0x1.bcb716596ef52p-2 + in[i] * (-0x1.bd63370d3230bp-3 + in[i] * (0x1.29146dae7a7fap-3 + in[i] * (-0x1.a2d646531efa7p-4 + in[i] * (0x1.4c8f0e906d925p-4 + in[i] * (-0x1.c00bb72eb21a3p-4 + in[i] * 0x1.85d51e35149d8p-4)))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.593e06a240da5p-19 + in[idx] * (0x1.bcb716596ef52p-2 + in[idx] * (-0x1.bd63370d3230bp-3 + in[idx] * (0x1.29146dae7a7fap-3 + in[idx] * (-0x1.a2d646531efa7p-4 + in[idx] * (0x1.4c8f0e906d925p-4 + in[idx] * (-0x1.c00bb72eb21a3p-4 + in[idx] * 0x1.85d51e35149d8p-4)))))));
										 });
#endif
	}

	// --- Log10 Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLog10Approximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (-0x1.34p-140 + in[i] * (0x1.ba7fcf54cef43p-2 + in[i] * (-0x1.b8f9959f4d36ap-3 + in[i] * (0x1.6c3993f2609ap-3 + in[i] * -0x1.1762797a9d07cp-3))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (-0x1.34p-140 + in[idx] * (0x1.ba7fcf54cef43p-2 + in[idx] * (-0x1.b8f9959f4d36ap-3 + in[idx] * (0x1.6c3993f2609ap-3 + in[idx] * -0x1.1762797a9d07cp-3))));
										 });
#endif
	}

	// Sin - sine, x * Horner(x^2, c)
	// Balanced:    6 terms (f32)   9 terms (f64)
	// Approximate: 4 terms (f32)   6 terms (f64)

	// --- Sin Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarSinBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.1p-1f + in[i] * (-0x1.555556p-3f + in[i] * (0x1.111112p-7f + in[i] * (-0x1.a019f8p-13f + in[i] * (0x1.71d732p-19f + in[i] * -0x1.a9508p-26f)))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.1p-1f + in[idx] * (-0x1.555556p-3f + in[idx] * (0x1.111112p-7f + in[idx] * (-0x1.a019f8p-13f + in[idx] * (0x1.71d732p-19f + in[idx] * -0x1.a9508p-26f)))));
										 });
#endif
	}

	// --- Sin Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarSinApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.1p-1f + in[i] * (-0x1.55554p-3f + in[i] * (0x1.11062ep-7f + in[i] * -0x1.9906cap-13f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.1p-1f + in[idx] * (-0x1.55554p-3f + in[idx] * (0x1.11062ep-7f + in[idx] * -0x1.9906cap-13f)));
										 });
#endif
	}

	// --- Sin Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarSinBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.1p-1 + in[i] * (-0x1.5555555555555p-3 + in[i] * (0x1.1111111111111p-7 + in[i] * (-0x1.a01a01a01a014p-13 + in[i] * (0x1.71de3a556bb7ep-19 + in[i] * (-0x1.ae64567d9d7a9p-26 + in[i] * (0x1.61245edeb306ap-33 + in[i] * (-0x1.ae7b75b7f3ea8p-41 + in[i] * 0x1.91e5d3ff5106bp-49))))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.1p-1 + in[idx] * (-0x1.5555555555555p-3 + in[idx] * (0x1.1111111111111p-7 + in[idx] * (-0x1.a01a01a01a014p-13 + in[idx] * (0x1.71de3a556bb7ep-19 + in[idx] * (-0x1.ae64567d9d7a9p-26 + in[idx] * (0x1.61245edeb306ap-33 + in[idx] * (-0x1.ae7b75b7f3ea8p-41 + in[idx] * 0x1.91e5d3ff5106bp-49))))))));
										 });
#endif
	}

	// --- Sin Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarSinApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.fffffffffffd9p-1 + in[i] * (-0x1.5555555550efep-3 + in[i] * (0x1.1111110bde5e3p-7 + in[i] * (-0x1.a019f8a207d3fp-13 + in[i] * (0x1.71d7317b8ee33p-19 + in[i] * -0x1.a9507f3711e2dp-26)))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.fffffffffffd9p-1 + in[idx] * (-0x1.5555555550efep-3 + in[idx] * (0x1.1111110bde5e3p-7 + in[idx] * (-0x1.a019f8a207d3fp-13 + in[idx] * (0x1.71d7317b8ee33p-19 + in[idx] * -0x1.a9507f3711e2dp-26)))));
										 });
#endif
	}

	// Cos - cosine, Horner(x^2, c)
	// Balanced:    6 terms (f32)   9 terms (f64)
	// Approximate: 4 terms (f32)   6 terms (f64)

	// --- Cos Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarCosBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.1p-1f + in[i] * (-0x1.1p-2f + in[i] * (0x1.555556p-5f + in[i] * (-0x1.6c16b2p-10f + in[i] * (0x1.a00e96p-16f + in[i] * -0x1.23c5c2p-22f)))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.1p-1f + in[idx] * (-0x1.1p-2f + in[idx] * (0x1.555556p-5f + in[idx] * (-0x1.6c16b2p-10f + in[idx] * (0x1.a00e96p-16f + in[idx] * -0x1.23c5c2p-22f)))));
										 });
#endif
	}

	// --- Cos Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarCosApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.1p-1f + in[i] * (-0x1.ffffap-2f + in[i] * (0x1.553ce6p-5f + in[i] * -0x1.6424ap-10f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.1p-1f + in[idx] * (-0x1.ffffap-2f + in[idx] * (0x1.553ce6p-5f + in[idx] * -0x1.6424ap-10f)));
										 });
#endif
	}

	// --- Cos Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarCosBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.1p-1 + in[i] * (-0x1.1p-2 + in[i] * (0x1.5555555555555p-5 + in[i] * (-0x1.6c16c16c16c09p-10 + in[i] * (0x1.a01a01a01844fp-16 + in[i] * (-0x1.27e4fb7581302p-22 + in[i] * (0x1.1eed8c32f1021p-29 + in[i] * (-0x1.9392cccc6be36p-37 + in[i] * 0x1.aa9bc439ae3a9p-45))))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.1p-1 + in[idx] * (-0x1.1p-2 + in[idx] * (0x1.5555555555555p-5 + in[idx] * (-0x1.6c16c16c16c09p-10 + in[idx] * (0x1.a01a01a01844fp-16 + in[idx] * (-0x1.27e4fb7581302p-22 + in[idx] * (0x1.1eed8c32f1021p-29 + in[idx] * (-0x1.9392cccc6be36p-37 + in[idx] * 0x1.aa9bc439ae3a9p-45))))))));
										 });
#endif
	}

	// --- Cos Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarCosApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.ffffffffffe0bp-1 + in[i] * (-0x1.ffffffffe3763p-2 + in[i] * (0x1.5555554476425p-5 + in[i] * (-0x1.6c16b2d3e61f5p-10 + in[i] * (0x1.a00e9685da9c4p-16 + in[i] * -0x1.23c5c15441ap-22)))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.ffffffffffe0bp-1 + in[idx] * (-0x1.ffffffffe3763p-2 + in[idx] * (0x1.5555554476425p-5 + in[idx] * (-0x1.6c16b2d3e61f5p-10 + in[idx] * (0x1.a00e9685da9c4p-16 + in[idx] * -0x1.23c5c15441ap-22)))));
										 });
#endif
	}

	// Tan - tangent, x * Horner(x^2, c)
	// Balanced:    6 terms (f32)   9 terms (f64)
	// Approximate: 4 terms (f32)   6 terms (f64)

	// --- Tan Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarTanBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.fffff8p-1f + in[i] * (0x1.555c1ap-2f + in[i] * (0x1.10158ep-3f + in[i] * (0x1.d44a86p-5f + in[i] * (0x1.9bb3ccp-7f + in[i] * 0x1.4db42ap-6f)))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.fffff8p-1f + in[idx] * (0x1.555c1ap-2f + in[idx] * (0x1.10158ep-3f + in[idx] * (0x1.d44a86p-5f + in[idx] * (0x1.9bb3ccp-7f + in[idx] * 0x1.4db42ap-6f)))));
										 });
#endif
	}

	// --- Tan Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarTanApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.fffa5ap-1f + in[i] * (0x1.579a9p-2f + in[i] * (0x1.db9ee4p-4f + in[i] * 0x1.80ebbap-4f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.fffa5ap-1f + in[idx] * (0x1.579a9p-2f + in[idx] * (0x1.db9ee4p-4f + in[idx] * 0x1.80ebbap-4f)));
										 });
#endif
	}

	// --- Tan Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarTanBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.000000005a5b8p+0 + in[i] * (0x1.555553e31f706p-2 + in[i] * (0x1.11118d1f228a7p-3 + in[i] * (0x1.b9fbd9de55dfcp-5 + in[i] * (0x1.68548d37e29e3p-6 + in[i] * (0x1.10332abe2f058p-7 + in[i] * (0x1.49f42392f1bf8p-8 + in[i] * (-0x1.4c5d8d7f2d263p-11 + in[i] * 0x1.0d67c14888fd1p-9))))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.000000005a5b8p+0 + in[idx] * (0x1.555553e31f706p-2 + in[idx] * (0x1.11118d1f228a7p-3 + in[idx] * (0x1.b9fbd9de55dfcp-5 + in[idx] * (0x1.68548d37e29e3p-6 + in[idx] * (0x1.10332abe2f058p-7 + in[idx] * (0x1.49f42392f1bf8p-8 + in[idx] * (-0x1.4c5d8d7f2d263p-11 + in[idx] * 0x1.0d67c14888fd1p-9))))))));
										 });
#endif
	}

	// --- Tan Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarTanApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.fffff88c9c162p-1 + in[i] * (0x1.555c1aa017c8fp-2 + in[i] * (0x1.10158d12320c6p-3 + in[i] * (0x1.d44a862e47de4p-5 + in[i] * (0x1.9bb3cce75e6a5p-7 + in[i] * 0x1.4db42acf4e25ep-6)))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.fffff88c9c162p-1 + in[idx] * (0x1.555c1aa017c8fp-2 + in[idx] * (0x1.10158d12320c6p-3 + in[idx] * (0x1.d44a862e47de4p-5 + in[idx] * (0x1.9bb3cce75e6a5p-7 + in[idx] * 0x1.4db42acf4e25ep-6)))));
										 });
#endif
	}

	// Asin - arcsine, x * Horner(x^2, c)
	// Balanced:    5 terms (f32)   8 terms (f64)
	// Approximate: 3 terms (f32)   5 terms (f64)

	// --- Asin Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAsinBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.000002p+0f + in[i] * (0x1.554dcp-3f + in[i] * (0x1.350eaep-4f + in[i] * (0x1.45ffp-5f + in[i] * 0x1.9c87b6p-5f))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.000002p+0f + in[idx] * (0x1.554dcp-3f + in[idx] * (0x1.350eaep-4f + in[idx] * (0x1.45ffp-5f + in[idx] * 0x1.9c87b6p-5f))));
										 });
#endif
	}

	// --- Asin Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAsinApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0001e4p+0f + in[i] * (0x1.5120dp-3f + in[i] * 0x1.87ef0cp-4f));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0001e4p+0f + in[idx] * (0x1.5120dp-3f + in[idx] * 0x1.87ef0cp-4f));
										 });
#endif
	}

	// --- Asin Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAsinBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.ffffffffe1fddp-1 + in[i] * (0x1.55555644ffd27p-3 + in[i] * (0x1.3332974333413p-4 + in[i] * (0x1.6ddd3297735ebp-5 + in[i] * (0x1.ed3310aa58a51p-6 + in[i] * (0x1.93e1363c82c76p-6 + in[i] * (0x1.e5084c0c9e239p-8 + in[i] * 0x1.1ca8ba846c6cbp-5)))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.ffffffffe1fddp-1 + in[idx] * (0x1.55555644ffd27p-3 + in[idx] * (0x1.3332974333413p-4 + in[idx] * (0x1.6ddd3297735ebp-5 + in[idx] * (0x1.ed3310aa58a51p-6 + in[idx] * (0x1.93e1363c82c76p-6 + in[idx] * (0x1.e5084c0c9e239p-8 + in[idx] * 0x1.1ca8ba846c6cbp-5)))))));
										 });
#endif
	}

	// --- Asin Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAsinApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.00000137fe155p+0 + in[i] * (0x1.554dbf185abeep-3 + in[i] * (0x1.350eaed06a2d5p-4 + in[i] * (0x1.45feff0af4e96p-5 + in[i] * 0x1.9c87b69ffd0f5p-5))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.00000137fe155p+0 + in[idx] * (0x1.554dbf185abeep-3 + in[idx] * (0x1.350eaed06a2d5p-4 + in[idx] * (0x1.45feff0af4e96p-5 + in[idx] * 0x1.9c87b69ffd0f5p-5))));
										 });
#endif
	}

	// Atan - arctangent, x * Horner(x^2, c)
	// Balanced:    6 terms (f32)   10 terms (f64)
	// Approximate: 4 terms (f32)   6 terms (f64)

	// --- Atan Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAtanBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.ffff52p-1f + in[i] * (-0x1.54f2b6p-2f + in[i] * (0x1.9011ep-3f + in[i] * (-0x1.ed5b7ep-4f + in[i] * (0x1.cf95ccp-5f + in[i] * -0x1.ae41ap-7f)))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.ffff52p-1f + in[idx] * (-0x1.54f2b6p-2f + in[idx] * (0x1.9011ep-3f + in[idx] * (-0x1.ed5b7ep-4f + in[idx] * (0x1.cf95ccp-5f + in[idx] * -0x1.ae41ap-7f)))));
										 });
#endif
	}

	// --- Atan Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAtanApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.ffdf9ap-1f + in[i] * (-0x1.4d0938p-2f + in[i] * (0x1.3b964p-3f + in[i] * -0x1.633322p-5f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.ffdf9ap-1f + in[idx] * (-0x1.4d0938p-2f + in[idx] * (0x1.3b964p-3f + in[idx] * -0x1.633322p-5f)));
										 });
#endif
	}

	// --- Atan Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAtanBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.ffffffe79bf93p-1 + in[i] * (-0x1.55552f0db432p-2 + in[i] * (0x1.998f82493d066p-3 + in[i] * (-0x1.240b8d994abf9p-3 + in[i] * (0x1.bfc9e8c2b0243p-4 + in[i] * (-0x1.5601364b1cac3p-4 + in[i] * (0x1.d3ad79f53e142p-5 + in[i] * (-0x1.f148f2a829af1p-6 + in[i] * (0x1.57a8c747ed314p-7 + in[i] * -0x1.bdf39729124b6p-10)))))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.ffffffe79bf93p-1 + in[idx] * (-0x1.55552f0db432p-2 + in[idx] * (0x1.998f82493d066p-3 + in[idx] * (-0x1.240b8d994abf9p-3 + in[idx] * (0x1.bfc9e8c2b0243p-4 + in[idx] * (-0x1.5601364b1cac3p-4 + in[idx] * (0x1.d3ad79f53e142p-5 + in[idx] * (-0x1.f148f2a829af1p-6 + in[idx] * (0x1.57a8c747ed314p-7 + in[idx] * -0x1.bdf39729124b6p-10)))))))));
										 });
#endif
	}

	// --- Atan Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAtanApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.ffff52add7cbdp-1 + in[i] * (-0x1.54f2b56f390a5p-2 + in[i] * (0x1.9011df7c714e8p-3 + in[i] * (-0x1.ed5b7ee5714bep-4 + in[i] * (0x1.cf95ccf6dc4c9p-5 + in[i] * -0x1.ae41a0cc72a89p-7)))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.ffff52add7cbdp-1 + in[idx] * (-0x1.54f2b56f390a5p-2 + in[idx] * (0x1.9011df7c714e8p-3 + in[idx] * (-0x1.ed5b7ee5714bep-4 + in[idx] * (0x1.cf95ccf6dc4c9p-5 + in[idx] * -0x1.ae41a0cc72a89p-7)))));
										 });
#endif
	}

	// Sinh - hyperbolic sine, x * Horner(x^2, c)
	// Balanced:    4 terms (f32)   7 terms (f64)
	// Approximate: 3 terms (f32)   5 terms (f64)

	// --- Sinh Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarSinhBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.1p-1f + in[i] * (0x1.555556p-3f + in[i] * (0x1.1110a6p-7f + in[i] * 0x1.a17df2p-13f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.1p-1f + in[idx] * (0x1.555556p-3f + in[idx] * (0x1.1110a6p-7f + in[idx] * 0x1.a17df2p-13f)));
										 });
#endif
	}

	// --- Sinh Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarSinhApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0f + in[i] * (0x1.55547cp-3f + in[i] * 0x1.123d82p-7f));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0f + in[idx] * (0x1.55547cp-3f + in[idx] * 0x1.123d82p-7f));
										 });
#endif
	}

	// --- Sinh Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarSinhBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0 + in[i] * (0x1.5555555555555p-3 + in[i] * (0x1.1111111111113p-7 + in[i] * (0x1.a01a01a0185b8p-13 + in[i] * (0x1.71de3a5f3a85fp-19 + in[i] * (0x1.ae641aa4b3bc4p-26 + in[i] * 0x1.61d987751d063p-33))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0 + in[idx] * (0x1.5555555555555p-3 + in[idx] * (0x1.1111111111113p-7 + in[idx] * (0x1.a01a01a0185b8p-13 + in[idx] * (0x1.71de3a5f3a85fp-19 + in[idx] * (0x1.ae641aa4b3bc4p-26 + in[idx] * 0x1.61d987751d063p-33))))));
										 });
#endif
	}

	// --- Sinh Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarSinhApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0000000000006p+0 + in[i] * (0x1.5555555550d88p-3 + in[i] * (0x1.11111123bf154p-7 + in[i] * (0x1.a01994c849582p-13 + in[i] * 0x1.72e107c874de9p-19))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0000000000006p+0 + in[idx] * (0x1.5555555550d88p-3 + in[idx] * (0x1.11111123bf154p-7 + in[idx] * (0x1.a01994c849582p-13 + in[idx] * 0x1.72e107c874de9p-19))));
										 });
#endif
	}

	// Cosh - hyperbolic cosine, Horner(x^2, c)
	// Balanced:    4 terms (f32)   7 terms (f64)
	// Approximate: 3 terms (f32)   5 terms (f64)

	// --- Cosh Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarCoshBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.1p-1f + in[i] * (0x1.0p-1f + in[i] * (0x1.555464p-5f + in[i] * 0x1.6da754p-10f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.1p-1f + in[idx] * (0x1.0p-1f + in[idx] * (0x1.555464p-5f + in[idx] * 0x1.6da754p-10f)));
										 });
#endif
	}

	// --- Cosh Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarCoshApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.000002p+0f + in[i] * (0x1.fffd0ap-2f + in[i] * 0x1.576362p-5f));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.000002p+0f + in[idx] * (0x1.fffd0ap-2f + in[idx] * 0x1.576362p-5f));
										 });
#endif
	}

	// --- Cosh Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarCoshBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0 + in[i] * (0x1.1p-2 + in[i] * (0x1.555555555555dp-5 + in[i] * (0x1.6c16c16c13a9dp-10 + in[i] * (0x1.a01a01b27d442p-16 + in[i] * (0x1.27e4c358312d7p-22 + in[i] * 0x1.1f97684759d2cp-29))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0 + in[idx] * (0x1.1p-2 + in[idx] * (0x1.555555555555dp-5 + in[idx] * (0x1.6c16c16c13a9dp-10 + in[idx] * (0x1.a01a01b27d442p-16 + in[idx] * (0x1.27e4c358312d7p-22 + in[idx] * 0x1.1f97684759d2cp-29))))));
										 });
#endif
	}

	// --- Cosh Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarCoshApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.000000000003dp+0 + in[i] * (0x1.ffffffffe74f1p-2 + in[i] * (0x1.55555588b8403p-5 + in[i] * (0x1.6c162bb7d965cp-10 + in[i] * 0x1.a17df0d914d6cp-16))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.000000000003dp+0 + in[idx] * (0x1.ffffffffe74f1p-2 + in[idx] * (0x1.55555588b8403p-5 + in[idx] * (0x1.6c162bb7d965cp-10 + in[idx] * 0x1.a17df0d914d6cp-16))));
										 });
#endif
	}

	// Asinh - inverse hyperbolic sine, x * Horner(x^2, c)
	// Balanced:    5 terms (f32)   9 terms (f64)
	// Approximate: 3 terms (f32)   6 terms (f64)

	// --- Asinh Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAsinhBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.fffffp-1f + in[i] * (-0x1.5539f8p-3f + in[i] * (0x1.2f8124p-4f + in[i] * (-0x1.3ef194p-5f + in[i] * 0x1.ce028cp-7f))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.fffffp-1f + in[idx] * (-0x1.5539f8p-3f + in[idx] * (0x1.2f8124p-4f + in[idx] * (-0x1.3ef194p-5f + in[idx] * 0x1.ce028cp-7f))));
										 });
#endif
	}

	// --- Asinh Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAsinhApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.fff2ccp-1f + in[i] * (-0x1.4d786ap-3f + in[i] * 0x1.a622bcp-5f));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.fff2ccp-1f + in[idx] * (-0x1.4d786ap-3f + in[idx] * 0x1.a622bcp-5f));
										 });
#endif
	}

	// --- Asinh Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAsinhBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.ffffffffd31a3p-1 + in[i] * (-0x1.5555546833a3bp-3 + in[i] * (0x1.3332cb1306bap-4 + in[i] * (-0x1.6da50cdef9bd8p-5 + in[i] * (0x1.f03a9698a9a1ap-6 + in[i] * (-0x1.64a1d4e884e18p-6 + in[i] * (0x1.eb17f1de08ap-7 + in[i] * (-0x1.0afc2605b475ap-7 + in[i] * 0x1.38db71d294bacp-9))))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.ffffffffd31a3p-1 + in[idx] * (-0x1.5555546833a3bp-3 + in[idx] * (0x1.3332cb1306bap-4 + in[idx] * (-0x1.6da50cdef9bd8p-5 + in[idx] * (0x1.f03a9698a9a1ap-6 + in[idx] * (-0x1.64a1d4e884e18p-6 + in[idx] * (0x1.eb17f1de08ap-7 + in[idx] * (-0x1.0afc2605b475ap-7 + in[idx] * 0x1.38db71d294bacp-9))))))));
										 });
#endif
	}

	// --- Asinh Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAsinhApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.fffffeb87136cp-1 + in[i] * (-0x1.55525256d6e19p-3 + in[i] * (0x1.329cfb7132e28p-4 + in[i] * (-0x1.62b33c784e945p-5 + in[i] * (0x1.8f72d64b4487p-6 + in[i] * -0x1.165b11aa660f5p-7)))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.fffffeb87136cp-1 + in[idx] * (-0x1.55525256d6e19p-3 + in[idx] * (0x1.329cfb7132e28p-4 + in[idx] * (-0x1.62b33c784e945p-5 + in[idx] * (0x1.8f72d64b4487p-6 + in[idx] * -0x1.165b11aa660f5p-7)))));
										 });
#endif
	}

	// Acosh - acosh(1+u)=sqrt(2u)*Horner(u,c), u=x-1
	// Balanced:    5 terms (f32)   8 terms (f64)
	// Approximate: 3 terms (f32)   5 terms (f64)

	// --- Acosh Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAcoshBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.6a09e6p+0f + in[i] * (-0x1.e2b3dp-4f + in[i] * (0x1.b1697p-6f + in[i] * (-0x1.ecfc96p-8f + in[i] * 0x1.cc0298p-10f))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.6a09e6p+0f + in[idx] * (-0x1.e2b3dp-4f + in[idx] * (0x1.b1697p-6f + in[idx] * (-0x1.ecfc96p-8f + in[idx] * 0x1.cc0298p-10f))));
										 });
#endif
	}

	// --- Acosh Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAcoshApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.6a084ep+0f + in[i] * (-0x1.df194cp-4f + in[i] * 0x1.611af2p-6f));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.6a084ep+0f + in[idx] * (-0x1.df194cp-4f + in[idx] * 0x1.611af2p-6f));
										 });
#endif
	}

	// --- Acosh Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAcoshBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.6a09e667efe68p+0 + in[i] * (-0x1.e2b7dda271da1p-4 + in[i] * (0x1.b2721effa4bf4p-6 + in[i] * (-0x1.0294304858003p-7 + in[i] * (0x1.5f548154f92bfp-9 + in[i] * (-0x1.fabbd22ca2814p-11 + in[i] * (0x1.5677d4f887a75p-12 + in[i] * -0x1.2dd8e606c72cbp-14)))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.6a09e667efe68p+0 + in[idx] * (-0x1.e2b7dda271da1p-4 + in[idx] * (0x1.b2721effa4bf4p-6 + in[idx] * (-0x1.0294304858003p-7 + in[idx] * (0x1.5f548154f92bfp-9 + in[idx] * (-0x1.fabbd22ca2814p-11 + in[idx] * (0x1.5677d4f887a75p-12 + in[idx] * -0x1.2dd8e606c72cbp-14)))))));
										 });
#endif
	}

	// --- Acosh Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAcoshApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.6a09e5c26a954p+0 + in[i] * (-0x1.e2b3cf54b0e0dp-4 + in[i] * (0x1.b16970f172561p-6 + in[i] * (-0x1.ecfc95a0a290dp-8 + in[i] * 0x1.cc0297ccbef79p-10))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.6a09e5c26a954p+0 + in[idx] * (-0x1.e2b3cf54b0e0dp-4 + in[idx] * (0x1.b16970f172561p-6 + in[idx] * (-0x1.ecfc95a0a290dp-8 + in[idx] * 0x1.cc0297ccbef79p-10))));
										 });
#endif
	}

	// Atanh - inverse hyperbolic tangent, x * Horner(x^2, c)
	// Balanced:    5 terms (f32)   8 terms (f64)
	// Approximate: 3 terms (f32)   5 terms (f64)

	// --- Atanh Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAtanhBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.000006p+0f + in[i] * (0x1.55452p-2f + in[i] * (0x1.9d8f88p-3f + in[i] * (0x1.f4c8aep-4f + in[i] * 0x1.8fc48ap-3f))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.000006p+0f + in[idx] * (0x1.55452p-2f + in[idx] * (0x1.9d8f88p-3f + in[idx] * (0x1.f4c8aep-4f + in[idx] * 0x1.8fc48ap-3f))));
										 });
#endif
	}

	// --- Atanh Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAtanhApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.00064cp+0f + in[i] * (0x1.4e542ep-2f + in[i] * 0x1.12cebcp-2f));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.00064cp+0f + in[idx] * (0x1.4e542ep-2f + in[idx] * 0x1.12cebcp-2f));
										 });
#endif
	}

	// --- Atanh Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAtanhBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.ffffffff5e368p-1 + in[i] * (0x1.555557db56886p-2 + in[i] * (0x1.9997f57975c75p-3 + in[i] * (0x1.24c5e33e88f82p-3 + in[i] * (0x1.c0f55975c35e6p-4 + in[i] * (0x1.a66a48ce8cef7p-4 + in[i] * (0x1.859eb5c8eb941p-6 + in[i] * 0x1.69d411adf045dp-3)))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.ffffffff5e368p-1 + in[idx] * (0x1.555557db56886p-2 + in[idx] * (0x1.9997f57975c75p-3 + in[idx] * (0x1.24c5e33e88f82p-3 + in[idx] * (0x1.c0f55975c35e6p-4 + in[idx] * (0x1.a66a48ce8cef7p-4 + in[idx] * (0x1.859eb5c8eb941p-6 + in[idx] * 0x1.69d411adf045dp-3)))))));
										 });
#endif
	}

	// --- Atanh Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarAtanhApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.000005356fbd4p+0 + in[i] * (0x1.5545203965275p-2 + in[i] * (0x1.9d8f88475479ap-3 + in[i] * (0x1.f4c8aeef23538p-4 + in[i] * 0x1.8fc48a7c4bd6dp-3))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.000005356fbd4p+0 + in[idx] * (0x1.5545203965275p-2 + in[idx] * (0x1.9d8f88475479ap-3 + in[idx] * (0x1.f4c8aeef23538p-4 + in[idx] * 0x1.8fc48a7c4bd6dp-3))));
										 });
#endif
	}

	// Erf - error function, x * Horner(x^2, c)
	// Balanced:    6 terms (f32)   10 terms (f64)
	// Approximate: 4 terms (f32)   6 terms (f64)

	// --- Erf Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarErfBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.20dd74p+0f + in[i] * (-0x1.81268p-2f + in[i] * (0x1.ce0ab2p-4f + in[i] * (-0x1.b5b31p-6f + in[i] * (0x1.428d76p-8f + in[i] * -0x1.281efap-11f)))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.20dd74p+0f + in[idx] * (-0x1.81268p-2f + in[idx] * (0x1.ce0ab2p-4f + in[idx] * (-0x1.b5b31p-6f + in[idx] * (0x1.428d76p-8f + in[idx] * -0x1.281efap-11f)))));
										 });
#endif
	}

	// --- Erf Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarErfApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.20db82p+0f + in[i] * (-0x1.802cbcp-2f + in[i] * (0x1.ba0bcep-4f + in[i] * -0x1.2dded4p-6f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.20db82p+0f + in[idx] * (-0x1.802cbcp-2f + in[idx] * (0x1.ba0bcep-4f + in[idx] * -0x1.2dded4p-6f)));
										 });
#endif
	}

	// --- Erf Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarErfBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.20dd750429b19p+0 + in[i] * (-0x1.812746b0271ecp-2 + in[i] * (0x1.ce2f2197bc2efp-4 + in[i] * (-0x1.b82ce15c3b7f8p-6 + in[i] * (0x1.565ba0406c001p-8 + in[i] * (-0x1.c0286cad68e02p-11 + in[i] * (0x1.f941bed7e7847p-14 + in[i] * (-0x1.f0705a1dde9aap-17 + in[i] * (0x1.9ae0986f9de4fp-20 + in[i] * -0x1.c1a515de8637ap-24)))))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.20dd750429b19p+0 + in[idx] * (-0x1.812746b0271ecp-2 + in[idx] * (0x1.ce2f2197bc2efp-4 + in[idx] * (-0x1.b82ce15c3b7f8p-6 + in[idx] * (0x1.565ba0406c001p-8 + in[idx] * (-0x1.c0286cad68e02p-11 + in[idx] * (0x1.f941bed7e7847p-14 + in[idx] * (-0x1.f0705a1dde9aap-17 + in[idx] * (0x1.9ae0986f9de4fp-20 + in[idx] * -0x1.c1a515de8637ap-24)))))))));
										 });
#endif
	}

	// --- Erf Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarErfApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.20dd74546d3e7p+0 + in[i] * (-0x1.812680a1a33f4p-2 + in[i] * (0x1.ce0ab171c3ee9p-4 + in[i] * (-0x1.b5b30f0f42c6cp-6 + in[i] * (0x1.428d76f2cc227p-8 + in[i] * -0x1.281ef9ed3249cp-11)))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.20dd74546d3e7p+0 + in[idx] * (-0x1.812680a1a33f4p-2 + in[idx] * (0x1.ce0ab171c3ee9p-4 + in[idx] * (-0x1.b5b30f0f42c6cp-6 + in[idx] * (0x1.428d76f2cc227p-8 + in[idx] * -0x1.281ef9ed3249cp-11)))));
										 });
#endif
	}

	// ErfcAsymptotic - erfc asymptotic, (exp(-x^2)/(x*sqrt(pi)))*Horner(1/x^2,c)
	// Balanced:    4 terms (f32)   4 terms (f64)
	// Approximate: 3 terms (f32)   3 terms (f64)

	// --- ErfcAsymptotic Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarErfcAsymptoticBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0f + in[i] * (-0x1.0p-1f + in[i] * (0x1.8p-1f + in[i] * -0x1.ep+0f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0f + in[idx] * (-0x1.0p-1f + in[idx] * (0x1.8p-1f + in[idx] * -0x1.ep+0f)));
										 });
#endif
	}

	// --- ErfcAsymptotic Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarErfcAsymptoticApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0f + in[i] * (-0x1.0p-1f + in[i] * 0x1.8p-1f));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0f + in[idx] * (-0x1.0p-1f + in[idx] * 0x1.8p-1f));
										 });
#endif
	}

	// --- ErfcAsymptotic Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarErfcAsymptoticBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0 + in[i] * (-0x1.0p-1 + in[i] * (0x1.8p-1 + in[i] * -0x1.ep+0)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0 + in[idx] * (-0x1.0p-1 + in[idx] * (0x1.8p-1 + in[idx] * -0x1.ep+0)));
										 });
#endif
	}

	// --- ErfcAsymptotic Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarErfcAsymptoticApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.0p+0 + in[i] * (-0x1.0p-1 + in[i] * 0x1.8p-1));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.0p+0 + in[idx] * (-0x1.0p-1 + in[idx] * 0x1.8p-1));
										 });
#endif
	}

	// SqrtSeed - sqrt seed for Newton-Raphson
	// Balanced:    5 terms (f32)   5 terms (f64)
	// Approximate: 4 terms (f32)   4 terms (f64)

	// --- SqrtSeed Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarSqrtSeedBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.669044p-3f + in[i] * (0x1.433fa4p+0f + in[i] * (-0x1.ac8a38p-1f + in[i] * (0x1.df42c2p-2f + in[i] * -0x1.42c35ap-4f))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.669044p-3f + in[idx] * (0x1.433fa4p+0f + in[idx] * (-0x1.ac8a38p-1f + in[idx] * (0x1.df42c2p-2f + in[idx] * -0x1.42c35ap-4f))));
										 });
#endif
	}

	// --- SqrtSeed Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarSqrtSeedApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.669044p-3f + in[i] * (0x1.433fa4p+0f + in[i] * (-0x1.ac8a38p-1f + in[i] * 0x1.df42c2p-2f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.669044p-3f + in[idx] * (0x1.433fa4p+0f + in[idx] * (-0x1.ac8a38p-1f + in[idx] * 0x1.df42c2p-2f)));
										 });
#endif
	}

	// --- SqrtSeed Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarSqrtSeedBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.669044b27e55fp-3 + in[i] * (0x1.433fa4f9223f1p+0 + in[i] * (-0x1.ac8a37f93cd48p-1 + in[i] * (0x1.df42c1629a518p-2 + in[i] * -0x1.42c35908092b3p-4))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.669044b27e55fp-3 + in[idx] * (0x1.433fa4f9223f1p+0 + in[idx] * (-0x1.ac8a37f93cd48p-1 + in[idx] * (0x1.df42c1629a518p-2 + in[idx] * -0x1.42c35908092b3p-4))));
										 });
#endif
	}

	// --- SqrtSeed Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarSqrtSeedApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.669044b27e55fp-3 + in[i] * (0x1.433fa4f9223f1p+0 + in[i] * (-0x1.ac8a37f93cd48p-1 + in[i] * 0x1.df42c1629a518p-2)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.669044b27e55fp-3 + in[idx] * (0x1.433fa4f9223f1p+0 + in[idx] * (-0x1.ac8a37f93cd48p-1 + in[idx] * 0x1.df42c1629a518p-2)));
										 });
#endif
	}

	// RsqrtSeed - rsqrt seed for Newton-Raphson
	// Balanced:    5 terms (f32)   5 terms (f64)
	// Approximate: 4 terms (f32)   4 terms (f64)

	// --- RsqrtSeed Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarRsqrtSeedBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.c6b9cep+0f + in[i] * (-0x1.67cdcep+0f + in[i] * (0x1.f3625ap-1f + in[i] * (-0x1.7d02f2p-2f + in[i] * 0x1.cd2876p-5f))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.c6b9cep+0f + in[idx] * (-0x1.67cdcep+0f + in[idx] * (0x1.f3625ap-1f + in[idx] * (-0x1.7d02f2p-2f + in[idx] * 0x1.cd2876p-5f))));
										 });
#endif
	}

	// --- RsqrtSeed Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarRsqrtSeedApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.c6b9cep+0f + in[i] * (-0x1.67cdcep+0f + in[i] * (0x1.f3625ap-1f + in[i] * -0x1.7d02f2p-2f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.c6b9cep+0f + in[idx] * (-0x1.67cdcep+0f + in[idx] * (0x1.f3625ap-1f + in[idx] * -0x1.7d02f2p-2f)));
										 });
#endif
	}

	// --- RsqrtSeed Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarRsqrtSeedBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.c6b9cdfab5492p+0 + in[i] * (-0x1.67cdcdd30e8ddp+0 + in[i] * (0x1.f3625a4e67596p-1 + in[i] * (-0x1.7d02f10610a8p-2 + in[i] * 0x1.cd28767f57645p-5))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.c6b9cdfab5492p+0 + in[idx] * (-0x1.67cdcdd30e8ddp+0 + in[idx] * (0x1.f3625a4e67596p-1 + in[idx] * (-0x1.7d02f10610a8p-2 + in[idx] * 0x1.cd28767f57645p-5))));
										 });
#endif
	}

	// --- RsqrtSeed Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarRsqrtSeedApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.c6b9cdfab5492p+0 + in[i] * (-0x1.67cdcdd30e8ddp+0 + in[i] * (0x1.f3625a4e67596p-1 + in[i] * -0x1.7d02f10610a8p-2)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.c6b9cdfab5492p+0 + in[idx] * (-0x1.67cdcdd30e8ddp+0 + in[idx] * (0x1.f3625a4e67596p-1 + in[idx] * -0x1.7d02f10610a8p-2)));
										 });
#endif
	}

	// CbrtSeed - cbrt seed for Newton-Raphson
	// Balanced:    5 terms (f32)   5 terms (f64)
	// Approximate: 4 terms (f32)   4 terms (f64)

	// --- CbrtSeed Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarCbrtSeedBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.395abp-1f + in[i] * (0x1.ba4fd4p-1f + in[i] * (-0x1.23bd2cp-1f + in[i] * (0x1.18e382p-2f + in[i] * -0x1.e2ee22p-5f))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.395abp-1f + in[idx] * (0x1.ba4fd4p-1f + in[idx] * (-0x1.23bd2cp-1f + in[idx] * (0x1.18e382p-2f + in[idx] * -0x1.e2ee22p-5f))));
										 });
#endif
	}

	// --- CbrtSeed Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarCbrtSeedApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.395abp-1f + in[i] * (0x1.ba4fd4p-1f + in[i] * (-0x1.23bd2cp-1f + in[i] * 0x1.18e382p-2f)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.395abp-1f + in[idx] * (0x1.ba4fd4p-1f + in[idx] * (-0x1.23bd2cp-1f + in[idx] * 0x1.18e382p-2f)));
										 });
#endif
	}

	// --- CbrtSeed Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarCbrtSeedBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.395aafeedb4p-1 + in[i] * (0x1.ba4fd4ac561dfp-1 + in[i] * (-0x1.23bd2bd853685p-1 + in[i] * (0x1.18e3815d16328p-2 + in[i] * -0x1.e2ee2147bdd1fp-5))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.395aafeedb4p-1 + in[idx] * (0x1.ba4fd4ac561dfp-1 + in[idx] * (-0x1.23bd2bd853685p-1 + in[idx] * (0x1.18e3815d16328p-2 + in[idx] * -0x1.e2ee2147bdd1fp-5))));
										 });
#endif
	}

	// --- CbrtSeed Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarCbrtSeedApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.395aafeedb4p-1 + in[i] * (0x1.ba4fd4ac561dfp-1 + in[i] * (-0x1.23bd2bd853685p-1 + in[i] * 0x1.18e3815d16328p-2)));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.395aafeedb4p-1 + in[idx] * (0x1.ba4fd4ac561dfp-1 + in[idx] * (-0x1.23bd2bd853685p-1 + in[idx] * 0x1.18e3815d16328p-2)));
										 });
#endif
	}

	// Lanczos - Lanczos gamma, rational sum g=7 9-term
	// Balanced:    9 terms (f32)   9 terms (f64)
	// Approximate: 8 terms (f32)   8 terms (f64)

	// --- Lanczos Balanced f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLanczosBalanced_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.1p-1f + in[i] * (0x1.52429cp+9f + in[i] * (-0x1.3ac8e8p+10f + in[i] * (0x1.81a966p+9f + in[i] * (-0x1.613ae6p+7f + in[i] * (0x1.903c28p+3f + in[i] * (-0x1.1bcb2ap-3f + in[i] * (0x1.4b045ap-17f + in[i] * 0x1.433a1cp-23f))))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.1p-1f + in[idx] * (0x1.52429cp+9f + in[idx] * (-0x1.3ac8e8p+10f + in[idx] * (0x1.81a966p+9f + in[idx] * (-0x1.613ae6p+7f + in[idx] * (0x1.903c28p+3f + in[idx] * (-0x1.1bcb2ap-3f + in[idx] * (0x1.4b045ap-17f + in[idx] * 0x1.433a1cp-23f))))))));
										 });
#endif
	}

	// --- Lanczos Approximate f32 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLanczosApproximate_f32(
			const Numerics::Float32* LEIBNIZ_RESTRICT in,
			Numerics::Float32* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.1p-1f + in[i] * (0x1.52429cp+9f + in[i] * (-0x1.3ac8e8p+10f + in[i] * (0x1.81a966p+9f + in[i] * (-0x1.613ae6p+7f + in[i] * (0x1.903c28p+3f + in[i] * (-0x1.1bcb2ap-3f + in[i] * 0x1.4b045ap-17f)))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.1p-1f + in[idx] * (0x1.52429cp+9f + in[idx] * (-0x1.3ac8e8p+10f + in[idx] * (0x1.81a966p+9f + in[idx] * (-0x1.613ae6p+7f + in[idx] * (0x1.903c28p+3f + in[idx] * (-0x1.1bcb2ap-3f + in[idx] * 0x1.4b045ap-17f)))))));
										 });
#endif
	}

	// --- Lanczos Balanced f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLanczosBalanced_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.ffffffffff95p-1 + in[i] * (0x1.52429b6c30b05p+9 + in[i] * (-0x1.3ac8e8ed4171bp+10 + in[i] * (0x1.81a9661d3b4d8p+9 + in[i] * (-0x1.613ae51a32f5dp+7 + in[i] * (0x1.903c27f8b9c81p+3 + in[i] * (-0x1.1bcb2992b2855p-3 + in[i] * (0x1.4b045a9e6c012p-17 + in[i] * 0x1.433a1cc831b75p-23))))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.ffffffffff95p-1 + in[idx] * (0x1.52429b6c30b05p+9 + in[idx] * (-0x1.3ac8e8ed4171bp+10 + in[idx] * (0x1.81a9661d3b4d8p+9 + in[idx] * (-0x1.613ae51a32f5dp+7 + in[idx] * (0x1.903c27f8b9c81p+3 + in[idx] * (-0x1.1bcb2992b2855p-3 + in[idx] * (0x1.4b045a9e6c012p-17 + in[idx] * 0x1.433a1cc831b75p-23))))))));
										 });
#endif
	}

	// --- Lanczos Approximate f64 ---
	template<size_t N> requires (N <= 8)
		LEIBNIZ_FORCEINLINE void unrolledScalarLanczosApproximate_f64(
			const Numerics::Float64* LEIBNIZ_RESTRICT in,
			Numerics::Float64* LEIBNIZ_RESTRICT out
		) {
		LEIBNIZ_ASSERT(in != nullptr);
		LEIBNIZ_ASSERT(out != nullptr);
		LEIBNIZ_ASSUME_ALIGNED(in, 32);
		LEIBNIZ_ASSUME_ALIGNED(out, 32);

#if LEIBNIZ_COMPILER_MSVC
		for (size_t i = 0; i < N; i++)
			out[i] = (0x1.ffffffffff95p-1 + in[i] * (0x1.52429b6c30b05p+9 + in[i] * (-0x1.3ac8e8ed4171bp+10 + in[i] * (0x1.81a9661d3b4d8p+9 + in[i] * (-0x1.613ae51a32f5dp+7 + in[i] * (0x1.903c27f8b9c81p+3 + in[i] * (-0x1.1bcb2992b2855p-3 + in[i] * 0x1.4b045a9e6c012p-17)))))));
#elif LEIBNIZ_COMPILER_CLANG || LEIBNIZ_COMPILER_GCC
		Utils::Unrolled::staticFor<0, N>([=](auto idx) {
			out[idx] = (0x1.ffffffffff95p-1 + in[idx] * (0x1.52429b6c30b05p+9 + in[idx] * (-0x1.3ac8e8ed4171bp+10 + in[idx] * (0x1.81a9661d3b4d8p+9 + in[idx] * (-0x1.613ae51a32f5dp+7 + in[idx] * (0x1.903c27f8b9c81p+3 + in[idx] * (-0x1.1bcb2992b2855p-3 + in[idx] * 0x1.4b045a9e6c012p-17)))))));
										 });
#endif
	}
} // namespace Leibniz::LinAlg::Internal::Kernels::Scalar