"""
Leibniz HPC Math Library — MathConstants generator
Produces MathConstants.h with hex float literals (0x1.XXXp+N).
"""

import mpmath
import math
import sys
sys.path.insert(0, "/home/claude")
from leibniz_fmt import set_prec, to_hex_float

FORMATS = [
    ("f32",    23,    "Float32",   "f",    True),
    ("f64",    52,    "Float64",   "",     True),
    ("f128",   112,   "Float128",  "",     False),
    ("f256",   232,   "Float256",  "",     False),
    ("f512",   479,   "Float512",  "",     False),
    ("f1024",  991,   "Float1024", "",     False),
]

def get_constants(mbits):
    set_prec(mbits)
    pi    = mpmath.pi
    e     = mpmath.e
    ln2   = mpmath.log(2)
    ln10  = mpmath.log(10)
    sqrt2 = mpmath.sqrt(2)
    sqrt3 = mpmath.sqrt(3)
    sqrt5 = mpmath.sqrt(5)
    return {
        "pi":              pi,
        "tau":             2 * pi,
        "euler":           e,
        "sqrt2":           sqrt2,
        "sqrt3":           sqrt3,
        "sqrt5":           sqrt5,
        "goldenRatio":     (1 + sqrt5) / 2,
        "ln2":             ln2,
        "ln10":            ln10,
        "log2e":           1 / ln2,
        "log10e":          1 / ln10,
        "log2_10":         ln10 / ln2,
        "log10_2":         ln2 / ln10,
        "invPi":           1 / pi,
        "invTwoPi":        1 / (2 * pi),
        "invE":            1 / e,
        "invLn2":          1 / ln2,
        "invLn10":         1 / ln10,
        "degToRad":        pi / 180,
        "radToDeg":        180 / pi,
        "eulerMascheroni": mpmath.euler,
        "catalan":         mpmath.catalan,
        "apery":           mpmath.apery,
    }

GROUPS = [
    ("Core",        ["pi", "tau", "euler", "sqrt2", "sqrt3", "sqrt5", "goldenRatio"]),
    ("Logarithmic", ["ln2", "ln10", "log2e", "log10e", "log2_10", "log10_2"]),
    ("Inverses",    ["invPi", "invTwoPi", "invE", "invLn2", "invLn10"]),
    ("Angle",       ["degToRad", "radToDeg"]),
    ("Special",     ["eulerMascheroni", "catalan", "apery"]),
]

COMMENTS = {
    "pi": "pi", "tau": "2 * pi", "euler": "Euler's number e",
    "sqrt2": "sqrt(2)", "sqrt3": "sqrt(3)", "sqrt5": "sqrt(5)",
    "goldenRatio": "(1 + sqrt(5)) / 2",
    "ln2": "log_e(2)", "ln10": "log_e(10)",
    "log2e": "log_2(e) = 1/ln2", "log10e": "log_10(e) = 1/ln10",
    "log2_10": "log_2(10) = ln10/ln2", "log10_2": "log_10(2) = ln2/ln10",
    "invPi": "1/pi", "invTwoPi": "1/(2*pi)", "invE": "1/e",
    "invLn2": "1/ln2", "invLn10": "1/ln10",
    "degToRad": "pi/180", "radToDeg": "180/pi",
    "eulerMascheroni": "Euler-Mascheroni gamma",
    "catalan": "Catalan's constant G",
    "apery": "Apery's constant zeta(3)",
}

def build():
    lines = []
    def L(s=""): lines.append(s)

    L("// AUTO-GENERATED by constants_gen.py — DO NOT EDIT BY HAND")
    L("// Leibniz HPC Math Library — Mathematical Constants")
    L("// All values use hex float literals (0x1.XXXp+N) for exact representation.")
    L("//")
    L("// Live:  Float32, Float64")
    L("// Stubs: Float128 / Float256 / Float512 / Float1024 (hex in comments)")
    L()
    L("#pragma once")
    L('#include "Leibniz.h"')
    L('#include "LeibnizFloat.h"')
    L('#include "LeibnizCompiler.h"')
    L('#include "LebnizDiagnostics.h"')
    L('#include "VectorizationTraits.h"')
    L()
    L("namespace Leibniz::Numerics::Constants {")
    L()
    L("\ttemplate<typename T>")
    L("\tstruct MathConstants;")
    L()

    for fmt_name, mbits, ctype, suffix, is_live in FORMATS:
        consts = get_constants(mbits)
        ctype_prim = "float" if suffix == "f" else "double"

        L(f"\t// {'='*68}")
        L(f"\t// {ctype} ({fmt_name}, {mbits}-bit mantissa)")
        L(f"\t// {'='*68}")
        L(f"\ttemplate<>")
        L(f"\tstruct MathConstants<{ctype}> final {{")
        L()
        for group_name, keys in GROUPS:
            L(f"\t\t// {group_name}")
            for key in keys:
                v       = consts[key]
                comment = COMMENTS[key]
                hex_lit = to_hex_float(v, mbits, suffix)
                if is_live:
                    L(f"\t\tstatic constexpr {ctype_prim} {key}() noexcept {{ return {hex_lit}; }} // {comment}")
                else:
                    L(f"\t\t// {comment}: {hex_lit}")
                    L(f"\t\tstatic constexpr double {key}() noexcept {{ return /* TODO */ 0.0; }}")
            L()
        L(f"\t}};")
        L()

    L("} // namespace Leibniz::Numerics::Constants")
    return "\n".join(lines)

if __name__ == "__main__":
    print("Generating MathConstants.h ...")
    output = build()
    with open("/home/claude/MathConstants.h", "w") as f:
        f.write(output)
    print(f"Done. Lines: {output.count(chr(10))}")
