import mpmath
import math
import sys
sys.path.insert(0, "/home/claude")
from leibniz_fmt import set_prec, to_hex_float

FP_FORMATS = [
    ("FP16",   "Float16",      10,    5,     True,    "",     15,           "Float16"),
    ("BF16",   "BFloat16",      7,    8,     True,    "",     127,          "BFloat16"),
    ("FP32",   "Float32",      23,    8,     True,    "f",    127,          "float"),
    ("FP64",   "Float64",      52,    11,    True,    "",     1023,         "double"),
    ("FP128",  "Float128",    112,    15,    False,   "",     16383,        "Float128"),
    ("FP256",  "Float256",    232,    23,    False,   "",     4194303,      "Float256"),
    ("FP512",  "Float512",    479,    32,    False,   "",     2147483647,   "Float512"),
    ("FP1024", "Float1024",   991,    32,    False,   "",     2147483647,   "Float1024"),
]

INT_BITS = [8, 16, 32, 64, 128, 256, 512, 1024]

def fp_limits(mbits, ebits, bias):
    set_prec(mbits + 64)
    epsilon       = mpmath.mpf(2) ** (-mbits)
    sqrt_epsilon  = mpmath.sqrt(epsilon)
    min_normal    = mpmath.mpf(2) ** (1 - bias)
    min_subnormal = mpmath.mpf(2) ** (1 - bias - mbits)
    emax          = (1 << ebits) - 2 - bias
    max_val       = (2 - mpmath.mpf(2) ** (-mbits)) * mpmath.mpf(2) ** emax
    return {
        "epsilon":        epsilon,
        "sqrtEpsilon":    sqrt_epsilon,
        "minNormal":      min_normal,
        "minSubnormal":   min_subnormal,
        "max":            max_val,
        "mantissaBits":   mbits,
        "exponentBits":   ebits,
        "exponentBias":   bias,
        "maxExponent":    emax,
        "minExponent":    1 - bias,
        "digits10":       int(mbits * math.log10(2)),
        "maxDigits10":    int(math.ceil((mbits + 1) * math.log10(2))) + 1,
    }

def int_limits(bits, signed):
    if signed:
        return -(2 ** (bits - 1)), 2 ** (bits - 1) - 1
    return 0, 2 ** bits - 1

def build():
    lines = []
    def L(s=""): lines.append(s)

    L("// AUTO-GENERATED by numeric_limits_gen.py — DO NOT EDIT BY HAND")
    L("// Leibniz HPC Math Library — NumericLimits")
    L("// All FP values use hex float literals (0x1.XXXp+N) for exact representation.")
    L()
    L("#pragma once")
    L('#include "Leibniz.h"')
    L('#include "LeibnizFloat.h"')
    L('#include "LeibnizCompiler.h"')
    L('#include "LeibnizDiagnostics.h"')
    L('#include "VectorizationTraits.h"')
    L()
    L("namespace Leibniz::Numerics::Limits {")
    L()
    L("\ttemplate<typename T>")
    L("\tstruct NumericLimits;")
    L()

    for fmt_name, ctype, mbits, ebits, is_live, suffix, bias, native_ctype in FP_FORMATS:
        lim = fp_limits(mbits, ebits, bias)
        ctype_prim = native_ctype

        L(f"\t// {'-'*66}")
        L(f"\t// {fmt_name}  ({ctype})  mantissa={mbits}  exponent={ebits}  bias={bias}")
        if not is_live:
            L(f"\t// Status: STUB — wire up {ctype} type first")
        L(f"\t// {'-'*66}")
        L(f"\ttemplate<>")
        L(f"\tstruct NumericLimits<{ctype}> final {{")
        L(f"\t\tstatic constexpr int mantissaBits = {mbits};")
        L(f"\t\tstatic constexpr int exponentBits = {ebits};")
        L(f"\t\tstatic constexpr int exponentBias = {bias};")
        L(f"\t\tstatic constexpr int maxExponent  = {lim['maxExponent']};")
        L(f"\t\tstatic constexpr int minExponent  = {lim['minExponent']};")
        L(f"\t\tstatic constexpr int digits10     = {lim['digits10']};")
        L(f"\t\tstatic constexpr int maxDigits10  = {lim['maxDigits10']};")
        L()

        def emit(name, val, comment):
            hex_lit = to_hex_float(val, mbits, suffix)
            if is_live:
                L(f"\t\tstatic constexpr {ctype_prim} {name}() noexcept {{ return {hex_lit}; }} // {comment}")
            else:
                L(f"\t\t// {comment}: {hex_lit}")
                L(f"\t\tstatic constexpr double {name}() noexcept {{ return /* TODO */ 0.0; }}")

        emit("epsilon",      lim["epsilon"],      "2^(-mantissaBits)")
        emit("sqrtEpsilon",  lim["sqrtEpsilon"],  "sqrt(epsilon)")
        emit("minNormal",    lim["minNormal"],     "smallest positive normal")
        emit("minSubnormal", lim["minSubnormal"],  "smallest positive subnormal")
        emit("max",          lim["max"],           "largest finite value")
        L(f"\t}};")
        L()

    L("\t// =====================================================================")
    L("\t// Integer Limits")
    L("\t// =====================================================================")
    L()
    L("\ttemplate<typename T>")
    L("\tstruct IntegerLimits;")
    L()

    for bits in INT_BITS:
        for signed in [True, False]:
            mn, mx = int_limits(bits, signed)
            prefix = "" if signed else "U"
            ctype  = f"{prefix}Int{bits}"
            is_native = bits <= 64

            L(f"\t// {'-'*66}")
            L(f"\t// {ctype}  ({bits}-bit {'signed' if signed else 'unsigned'})")
            L(f"\t// {'-'*66}")
            L(f"\ttemplate<>")
            L(f"\tstruct IntegerLimits<{ctype}> final {{")
            L(f"\t\tstatic constexpr int bits = {bits};")
            L()

            if is_native:
                ctype_prim = (
                    "signed char" if (signed and bits==8) else
                    "unsigned char" if (not signed and bits==8) else
                    "short" if (signed and bits==16) else
                    "unsigned short" if (not signed and bits==16) else
                    "int" if (signed and bits==32) else
                    "unsigned int" if (not signed and bits==32) else
                    "long long" if signed else
                    "unsigned long long"
                )
                mn_lit = f"{mn}" if mn >= -(2**31) else f"{mn}LL"
                mx_lit = f"{mx}" if mx <= 2**31-1 else (f"{mx}ULL" if not signed else f"{mx}LL")
                L(f"\t\tstatic constexpr {ctype_prim} min() noexcept {{ return {mn_lit}; }}")
                L(f"\t\tstatic constexpr {ctype_prim} max() noexcept {{ return {mx_lit}; }}")
            else:
                mn_hex = f"-0x{abs(mn):X}" if mn < 0 else f"0x{mn:X}"
                mx_hex = f"0x{mx:X}"
                L(f"\t\t// min: {mn_hex}")
                L(f"\t\t// max: {mx_hex}")
                L(f"\t\tstatic constexpr long long min() noexcept {{ return /* TODO */ 0; }}")
                L(f"\t\tstatic constexpr long long max() noexcept {{ return /* TODO */ 0; }}")

            L(f"\t}};")
            L()

    L("} // namespace Leibniz::Numerics::Limits")
    return "\n".join(lines)

if __name__ == "__main__":
    output = build()
    with open("/home/claude/NumericLimits.h", "w") as f:
        f.write(output)
    print(f"Done. Lines: {output.count(chr(10))}")
