"""
Leibniz HPC Math Library — NumericLimits generator
Produces NumericLimits.h covering:

Floating point:
  FP16 (ieeeHalfPrecision,            10-bit mantissa)
  BF16 (ieeeBrainPrecision,            7-bit mantissa)
  FP32 (ieeeSinglePrecision,          23-bit mantissa)
  FP64 (ieeeDoublePrecision,          52-bit mantissa)
  FP128  (ieeeQuadPrecision,         112-bit mantissa)  -- stub
  FP256  (leibnizOctaPrecision,      232-bit mantissa)  -- stub
  FP512  (leibnizHalfRefWidthPrecision, 479-bit mantissa) -- stub
  FP1024 (leibnizFullRefWidthPrecision, 991-bit mantissa) -- stub

Integer (signed and unsigned):
  8, 16, 32, 64, 128, 256, 512, 1024 bit
"""

import mpmath
import math
import sys
sys.path.insert(0, "/home/claude")
from leibniz_fmt import set_prec, to_hex_float

# ---------------------------------------------------------------------------
# FP format table
# ---------------------------------------------------------------------------
FP_FORMATS = [
    # name      ctype          mbits  ebits  is_live  suffix  bias          native_ctype
    ("FP16",   "Float16",      10,    5,     True,    "",     15,           "Float16"),
    ("BF16",   "BFloat16",      7,    8,     True,    "",     127,          "BFloat16"),
    ("FP32",   "Float32",      23,    8,     True,    "f",    127,          "float"),
    ("FP64",   "Float64",      52,    11,    True,    "",     1023,         "double"),
    ("FP128",  "Float128",    112,    15,    False,   "",     16383,        "Float128"),
    ("FP256",  "Float256",    232,    23,    False,   "",     4194303,      "Float256"),
    ("FP512",  "Float512",    479,    32,    False,   "",     2147483647,   "Float512"),
    ("FP1024", "Float1024",   991,    32,    False,   "",     2147483647,   "Float1024"),
]

# ---------------------------------------------------------------------------
# Integer format table
# ---------------------------------------------------------------------------
INT_BITS = [8, 16, 32, 64, 128, 256, 512, 1024]

# ---------------------------------------------------------------------------
# FP limit computation
# ---------------------------------------------------------------------------

def fp_limits(mbits, ebits, bias):
    set_prec(mbits + 64)

    # epsilon: smallest x such that 1 + x != 1 = 2^(-mbits)
    epsilon      = mpmath.mpf(2) ** (-mbits)
    sqrt_epsilon = mpmath.sqrt(epsilon)

    # min positive normal: 2^(1 - bias)
    min_normal   = mpmath.mpf(2) ** (1 - bias)

    # min positive subnormal: 2^(1 - bias - mbits)
    min_subnormal = mpmath.mpf(2) ** (1 - bias - mbits)

    # max finite: (2 - 2^(-mbits)) * 2^(emax)
    emax         = (1 << ebits) - 2 - bias   # = 2^(ebits-1) - 1
    max_val      = (2 - mpmath.mpf(2) ** (-mbits)) * mpmath.mpf(2) ** emax

    # log10 of max (digits of range)
    log10_max    = mpmath.log10(max_val)
    log10_eps    = -mbits * mpmath.log10(2)

    return {
        "epsilon":        epsilon,
        "sqrtEpsilon":    sqrt_epsilon,
        "minNormal":      min_normal,
        "minSubnormal":   min_subnormal,
        "max":            max_val,
        "mantissaBits":   mbits,
        "exponentBits":   ebits,
        "exponentBias":   bias,
        "maxExponent":    emax,
        "minExponent":    1 - bias,
        "digits10":       int(mbits * math.log10(2)),       # significant decimal digits
        "maxDigits10":    int(math.ceil((mbits + 1) * math.log10(2))) + 1,
        "log10_epsilon":  log10_eps,
    }

# ---------------------------------------------------------------------------
# Integer limit computation
# ---------------------------------------------------------------------------

def int_limits(bits, signed):
    if signed:
        mn = -(2 ** (bits - 1))
        mx =   2 ** (bits - 1) - 1
    else:
        mn = 0
        mx = 2 ** bits - 1
    return mn, mx

def int_hex(val, bits, signed):
    """Format integer as 0x... hex literal."""
    if val == 0:
        return "0x0"
    if val < 0:
        # Two's complement unsigned representation
        uval = val + 2 ** bits
        return f"-0x{uval:X}  /* {val} */"
    return f"0x{val:X}"

# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------

def build():
    lines = []
    def L(s=""): lines.append(s)

    L("// AUTO-GENERATED by numeric_limits_gen.py — DO NOT EDIT BY HAND")
    L("// Leibniz HPC Math Library — NumericLimits")
    L("//")
    L("// Covers:")
    L("//   Floating point: FP16, BF16, FP32, FP64 (live)")
    L("//                   FP128, FP256, FP512, FP1024 (stubs — wire up type first)")
    L("//   Integer:        INT8..INT1024, UINT8..UINT1024")
    L("//")
    L("// All FP values use hex float literals (0x1.XXXp+N) for exact representation.")
    L("// Integer min/max use hex literals.")
    L()
    L("#pragma once")
    L('#include "Leibniz.h"')
    L('#include "LeibnizFloat.h"')
    L('#include "LeibnizCompiler.h"')
    L('#include "LeibnizDiagnostics.h"')
    L('#include "VectorizationTraits.h"')
    L()
    L("namespace Leibniz::Numerics::Limits {")
    L()

    # -----------------------------------------------------------------------
    # Floating point specializations
    # -----------------------------------------------------------------------
    L("\t// =====================================================================")
    L("\t// Floating Point Limits")
    L("\t// =====================================================================")
    L()
    L("\ttemplate<typename T>")
    L("\tstruct NumericLimits;")
    L()

    for fmt_name, ctype, mbits, ebits, is_live, suffix, bias, native_ctype in FP_FORMATS:
        lim = fp_limits(mbits, ebits, bias)

        ctype_prim = native_ctype

        L(f"\t// {'-'*66}")
        L(f"\t// {fmt_name}  ({ctype})  mantissa={mbits}  exponent={ebits}  bias={bias}")
        if not is_live:
            L(f"\t// Status: STUB — paste hex values once {ctype} is available")
        L(f"\t// {'-'*66}")
        L(f"\ttemplate<>")
        L(f"\tstruct NumericLimits<{ctype}> final {{")
        L(f"\t\tstatic constexpr int  mantissaBits     = {mbits};")
        L(f"\t\tstatic constexpr int  exponentBits     = {ebits};")
        L(f"\t\tstatic constexpr int  exponentBias     = {bias};")
        L()

        def emit_fp_const(name, val, comment):
            if is_live:
                hex_lit = to_hex_float(val, mbits, suffix)
                L(f"\t\tstatic constexpr {ctype_prim} {name}() noexcept {{ return {hex_lit}; }} // {comment}")
            else:
                hex_lit = to_hex_float(val, mbits, "")
                L(f"\t\t// {comment}: {hex_lit}")
                L(f"\t\tstatic constexpr double {name}() noexcept {{ return /* TODO */ 0.0; }}")

        emit_fp_const("epsilon",      lim["epsilon"],      "2^(-mantissa), smallest x s.t. 1+x != 1")
        emit_fp_const("sqrtEpsilon",  lim["sqrtEpsilon"],  "sqrt(epsilon)")
        emit_fp_const("minNormal",    lim["minNormal"],    "smallest positive normal")
        emit_fp_const("minSubnormal", lim["minSubnormal"], "smallest positive subnormal (denorm)")
        emit_fp_const("max",          lim["max"],          "largest finite value")

        L(f"\t}};")
        L()

    # -----------------------------------------------------------------------
    # Integer specializations
    # -----------------------------------------------------------------------
    L("\t// =====================================================================")
    L("\t// Integer Limits")
    L("\t// =====================================================================")
    L()
    L("\ttemplate<typename T>")
    L("\tstruct IntegerLimits;")
    L()

    for bits in INT_BITS:
        for signed in [True, False]:
            mn, mx = int_limits(bits, signed)
            prefix = "" if signed else "U"
            ctype  = f"{prefix}Int{bits}"
            ctype_prim = "// underlying C++ type not available for >64-bit" if bits > 64 else (
                f"{'int' if signed else 'unsigned int'}" if bits == 32 else
                f"{'long long' if signed else 'unsigned long long'}" if bits == 64 else
                f"{'short' if signed else 'unsigned short'}" if bits == 16 else
                f"{'signed char' if signed else 'unsigned char'}"
            )
            is_native = bits <= 64

            L(f"\t// {'-'*66}")
            L(f"\t// {ctype}  ({bits}-bit {'signed' if signed else 'unsigned'})")
            L(f"\t// {'-'*66}")
            L(f"\ttemplate<>")
            L(f"\tstruct IntegerLimits<{ctype}> final {{")
            L(f"\t\tstatic constexpr int  bits            = {bits};")
            L()

            if is_native:
                mn_lit = f"{mn}" if mn >= -(2**31) else f"{mn}LL"
                mx_lit = f"{mx}" if mx <= 2**31-1 else (f"{mx}ULL" if not signed else f"{mx}LL")
                L(f"\t\tstatic constexpr {ctype_prim} min() noexcept {{ return {mn_lit}; }}")
                L(f"\t\tstatic constexpr {ctype_prim} max() noexcept {{ return {mx_lit}; }}")
            else:
                # Emit as hex comment + TODO stub
                mn_hex = f"-0x{(abs(mn)):X}" if mn < 0 else f"0x{mn:X}"
                mx_hex = f"0x{mx:X}"
                L(f"\t\t// min: {mn_hex}")
                L(f"\t\t// max: {mx_hex}")
                L(f"\t\t// TODO: return {ctype}::fromBits(...) once type is available")
                L(f"\t\tstatic constexpr long long min() noexcept {{ return /* TODO */ 0; }}")
                L(f"\t\tstatic constexpr long long max() noexcept {{ return /* TODO */ 0; }}")

            L(f"\t}};")
            L()

    L("} // namespace Leibniz::Numerics::Limits")
    return "\n".join(lines)


if __name__ == "__main__":
    print("Generating NumericLimits.h ...")
    output = build()
    with open("/home/claude/NumericLimits.h", "w") as f:
        f.write(output)
    print(f"Done. Lines: {output.count(chr(10))}")
